### ISSUE TITLE
TypeError in dropdown.js ?

### ISSUE THREAD

**Issue by MatRouault** [Formstone/Formstone#10]
Hello,

Thanks for these useful plugins. 
I can't get work the Dropdown.js. Firebug says:
"TypeError: c.$selected.touch is not a function"

M

**Comment by benplum** [comment]
You will need to include any dependencies when using a specific component. For Dropdown you need `core.js` as well as `touch.js`.

**Comment by ansuz** [comment]
I'm still having the same issue. [The dropdown module's guide](http://formstone.it/components/dropdown/) doesn't indicate that touch.js is a dependency. I added it, but the issue persisted.

Wrapping [this expression](https://github.com/Formstone/Formstone/blob/master/src/js/dropdown.js#L116-L118) in a conditional (`if(data.$selected && data.$selected.touch){`) prevented the typeError, but without a deeper understanding of everything that's happening in the lib I'm not sure if this will just cover up some deeper issue.

**Comment by benplum** [comment]
The dependencies are listed under 'Use': http://formstone.it/components/dropdown/#use

I can't replicate the problem. Can you provide a jsbin / codepen of your issue?

**Comment by ansuz** [comment]
I must have been looking at the wrong tab when I looked up the dependencies, sorry about that. I also managed to track down the issue to an intermittent gulp error (which my patch happened to address) but it looks like everything is indeed good on your end.

Thanks for the code and the quick response!

**Comment by benplum** [comment]
No worries!
