### ISSUE TITLE
Number input broken on iOS (iPhone + iPad)

### ISSUE THREAD

**Issue by thijskaspers** [Formstone/Formstone#101]
The numberpicker input is broken in iOS.. When a user clicks on the input field, the keyboard comes up, but nothing can be entered. The arrow buttons do work, but custom input isn't working.

You can test it here: https://formstone.it/components/number/

We've tried in iOS 8 and 9.

**Comment by benplum** [comment]
Are you looking at the simulator? You'll need to uncheck "Hardware > Keyboard > Connect Hardware Keyboard" to see ht keyboard popup.

**Comment by benplum** [comment]
It's also worth noting you'll need to add a `pattern` attribute for iOS to show the numeric keyboard:

`<input type="number" pattern="[0-9]*">`

This has been added to the docs.

**Comment by thijskaspers** [comment]
Hi Ben,

I'm not looking at the simulator. I'm visiting your official Formstone website (https://formstone.it/components/number/) on my iPhone and iPad. The bug is also present there.

You can't enter any numbers with the keyboard.. At least, they aren't visible... Sometimes they show up, but it is very buggy.

**Comment by benplum** [comment]
Tracked this down, was a rogue `user-select: none` style :/

**Comment by thijskaspers** [comment]
Sweet, thanks!
