### ISSUE TITLE
Number input delay to combo-increment too short

### ISSUE THREAD

**Issue by Abdillah** [Formstone/Formstone#104]
When users have usual click on the number arrow button, sometimes it increments twice of the step. I suspect it is due to [delay of the combo timer](https://github.com/Formstone/Formstone/blob/master/src/js/number.js#L136).

**Comment by benplum** [comment]
Do you have a specific browser you're seeing this in?

**Comment by benplum** [comment]
I've added a second timeout allowing for a longer delay on the initial press, then a shorter delay if held down.

**Comment by Abdillah** [comment]
Thanks, I will test it. I'm actually using latest firefox by default. Well, I'm not yet test on others.
