### ISSUE TITLE
Infinite Carousels

### ISSUE THREAD

**Issue by bliswebagency** [Formstone/Formstone#105]
Hi Ben,

First up, want to say, we all love Formstone. It's pretty incredible.

However, when it comes to the Carousel component, I'm unclear about what the "infinite" parameter does. Does this only work when you're viewing 1 cell at a time? 

I've got the following parameters:
{ show: 6, infinite: true, paged: true }

But once it hits the final element, the user has to wait until all 6 elements are gone before it loops again.

Is it possible to add an option so that the first element follows (floats next to) the last element?

(It would also be amazing if you could add swipe gestures to the mobile lightbox. Just a suggestion).

**Comment by benplum** [comment]
So 'infinite' just means when you hit the last page, "next" will jump back to the first (and animate in the opposite direction). I've seen other plugins use a true 'infinite', where the first item will appear after the last (and vice-versa), however this is not how Carousel currently works.

**Comment by benplum** [comment]
We may circle back here at a later date.

**Comment by TrangDinhVan** [comment]
Hello, is there any new for this? Thanks.
