### ISSUE TITLE
fs-dropdown-focus class isn't added to the dropdown

### ISSUE THREAD

**Issue by k-lusine** [Formstone/Formstone#107]
Hi, thanks for great plugin

I noticed that in the demo when I open a dropdown for the first time, it adds two new classes, fs-dropdown-focus and fs-dropdown-open, and when I close it, fs-dropdown-open is removed. I use the latest version, but it doesn't add fs-dropdown-focus class. Is there anything, I'm doing wrong. I need that class badly.

Thanks

**Comment by benplum** [comment]
I can't reproduce this - can you provide an example (codepen, pastebin)?

**Comment by k-lusine** [comment]
@benplum It turned out, that it isn't added locally, but when on a server, works okay
