### ISSUE TITLE
Dropdown does not behave like native select element when in a fixed height overflow:hidden container.

### ISSUE THREAD

**Issue by thinsoldier** [Formstone/Formstone#111]
![screen shot 2015-11-09 at 11 46 35 am](https://cloud.githubusercontent.com/assets/373834/11040017/53a9cf06-86d8-11e5-8ac7-3a3c4ce5995a.png)

The native select element's options list overflows the parent element even if the parent is set to overflow:hidden.

Maybe you could have the options list dom node temporarily moved to be a child of Body and positioned absolutely.

**Comment by thinsoldier** [comment]
lol, sorry. I added this issue already.

**Comment by benplum** [comment]
No worries, it's something we still don't have a great solution to since absolutely positioning content can introduce it's own problems (scroll, z-index, etc).
