### ISSUE TITLE
Dropdown: Select multiple options range with shift

### ISSUE THREAD

**Issue by CodeBrauer** [Formstone/Formstone#116]
(Native) When I select multiple options I press `CTRL` on Windows/Linux or `CMD` on Mac - so I can click every option to select it & `SHIFT` to select a range (from/to).

On _Formstone Dropdown_ you can't select a range like:
- Shift-click Option `One`
- Shift-click Option `Five`
- So `One, Two, Three, Four, Five` should be selected.

**Comment by benplum** [comment]
This would be a great enhancement to the plugin.

**Comment by benplum** [comment]
I'll tag a release at some point but this is on the master branch.
