### ISSUE TITLE
$.asap cache busting

### ISSUE THREAD

**Issue by pyronaur** [Formstone/Formstone#118]
Wonderful work on the framework! Loving $.asap!

One tiny issue for me - $.asap requests generate a cache buster, and I'd like to avoid that. I want my AJAX Requests to be cached. Can you add an option to disable it ?

**Comment by benplum** [comment]
I think we can work this in.

**Comment by pyronaur** [comment]
Do you need any help? If you could just point me in the right direction I can send you a pull request.

**Comment by benplum** [comment]
Looking at this again and the `cache` option on the $.ajax call is being set by the `cache` option in the plugin. If you have `cache` set to `true` (the default), requests should be cached. If this is set to `false`, jQuery will append a parameter to the request as outlined here: http://api.jquery.com/jquery.ajax/.

**Comment by pyronaur** [comment]
Wonderful. Tried `cache: true;` and it worked out flawlessly! Thanks!
