### ISSUE TITLE
Checkbox input doesn't get any value when checked

### ISSUE THREAD

**Issue by davidwieler** [Formstone/Formstone#12]
When clicking a checkbox, the value of the actual input element doesn't update the value attribute. The only thing that happens is the wrapping div gets the class "fs-checkbox-checked" added.

**Comment by benplum** [comment]
The value attribute is never updated on a checkbox or radio form element, just the ':checked' status. See this bin for a working example: http://jsbin.com/cewulo/5/edit?html,js,output
