### ISSUE TITLE
Upload: div of $('.upload') not the drop target

### ISSUE THREAD

**Issue by Valamas** [Formstone/Formstone#120]
I have a div with an existing image. i wish to update the image using drag and drop.
 `<div class="upload">`
 `<img src='myimage' />`
`</div>`

When I drag an image over the browser. Both the `<div class="upload">` and the `<div>Label</div>` highlight to indicate the drop target. However, only dropping the file on the LABEL will upload the file. Dropping off the label and on to `<div class='upload'>` itself will just have my browser show the image.

_Side mention_: I extended the customizable events to include filedragenter and filedragleave. My intention was to not show the LABEL unless the file was dragging over that upload class div. It has not worked for me yet but hope if I can get past the mentioned issue that I won't need the label as the fs-upload-dropping class is good enough indication. cheers.

**Comment by benplum** [comment]
Can you provide an example (jsbin or codepen)?
