### ISSUE TITLE
Cannot find a zoomer component

### ISSUE THREAD

**Issue by sergeykosik** [Formstone/Formstone#121]
Hi guys,
I cannot find a zoomer component, whereas it was mentioned to upgrade to new Formstone: https://github.com/FormstoneClassic/Zoomer 

Thanks.

**Comment by benplum** [comment]
This has not been moved over yet.

**Comment by benplum** [comment]
We've got an early version up: https://beta.formstone.it/components/viewer.html

**Comment by benplum** [comment]
This is ready to go and will ship with the next release.
