### ISSUE TITLE
Dropdown always on top

### ISSUE THREAD

**Issue by gioacostax** [Formstone/Formstone#124]
Im trying all with this dropdown and allways is on top... :(

![drop](https://cloud.githubusercontent.com/assets/5884099/11432744/88fb9dee-9482-11e5-8ba9-73e8991cc462.png)

**Comment by gioacostax** [comment]
Well, at finish I needed debug and found the problem...

``` javascript
// Calculate bottom of document
if (offset.top + optionsHeight > bodyHeight - data.bottomEdge) {
   data.$dropdown.addClass(RawClasses.bottom);
}
```

Why this condition?? when we need an alone dropdown in the middle of the body this is a problem...

:) Nice project...

**Comment by benplum** [comment]
The document may be too short, so the plugin thinks the dropdown is at the bottom of the `body` tag. You could try adding extra padding/margin around the dropdown to increase the `body` height.
