### ISSUE TITLE
onChange onInput doesn't work in range

### ISSUE THREAD

**Issue by anorudes** [Formstone/Formstone#128]
$("#range").range();

All code are not working:

```
    $('#range').on('change', function() {
      alert('1');
    });
```

```
    $('#range').on('input', function() {
      alert('1');
    });
```

```
    $(document).on('input', '#range', function() {
      alert('1');
    });
```

```
    $(document).on('change', '#range', function() {
      alert('1');
    });
```

I can get value only with setInterval:

```
    setInterval(function() {
      console.log($('#range').value());
    }, 1000)
```

How i can fix this?

**Comment by k-lusine** [comment]
I have the same issue, can't fix it

**Comment by anorudes** [comment]
Thanks, benplum, but is's not working with angular.
    <input type="range" id="filter-range" min="0" max="20" step="1"
                        ng-model="filter.price"
                        data-range-options='{"labels":{"min":"$ 0 млн","max":"$ 20 млн"}}'>

Model not changed after change range.

**Comment by anorudes** [comment]
code
```
  $('#range').on('change', function() {
    console.log('123');
  });
```
not working too
