### ISSUE TITLE
Checkbox on click event using jQuery

### ISSUE THREAD

**Issue by davidwieler** [Formstone/Formstone#13]
When the checkbox component is used with jQuery, the on('click') event is unusable.

**Comment by benplum** [comment]
The input will still receive it's click event. See this bin for a working example: http://jsbin.com/cewulo/5/edit?html,js,output

**Comment by davidwieler** [comment]
~~Sorry, should have explained more. The on click event works fine, however when you're clicking on an element that's been added to the DOM after the fact, it doesn't work.~~

Edit: It does work, however the `$().checkbox().on('click')` has to be called after each time something is added to the DOM, be it inline or after an AJAX call. I was doing it like this: `$('body').checkbox().on('click', '.someclass', function(){});` and expecting it to work. Easiest way is to just wrap `$("input[type=checkbox], input[type=radio]").checkbox().on("change", function() {console.log( $(this).is(":checked") );}).on("click", function() {console.log( $(this).is(":checked") );});` in a function and call it each time it's needed on new DOM elements.

**Comment by benplum** [comment]
Yes, you still need to initialize each instance, even if it's been to the DOM after the initial call.
