### ISSUE TITLE
Manually trigger upload

### ISSUE THREAD

**Issue by ghost** [Formstone/Formstone#130]
I have a use case where once a user drags a file to dropzone I need to do some basic Javascript validation and present some options based on file type. After that user needs to click Upload button to actually initiate upload action. I cannot find any method that can trigger processing upload queue. Can you please let me know if this is supported or possible using upload JS.

**Comment by benplum** [comment]
The upload process will begin automatically when files are selected/dropped. You can filter files using the `beforeSend` callback:

```
$(".target").upload({
    beforeSend: onBeforeSend
});

function onBeforeSend(formData, file) {
    // Cancel request
    if (file.name.indexOf(".jpg") < 0) {
        return false;
    }

    return formData;
}
```

**Comment by ghost** [comment]
Thanks for the response. My use case is little different.
1. Some way to automatically process the upload queue.
2. A method that is needed to be invoked manually for upload to begin.

As an example In this open source component dropzonejs they have a boolean component - autoProcessQueue.
http://www.dropzonejs.com/#config-autoProcessQueue

**Comment by benplum** [comment]
There is a new option in 0.8.35, `autoUpload`, that can be set to false. Then use the `start` method to begin uploading the queued files:

```
$(".upload").upload("start");
```

You can filter/cancel individual files by looping through the files passed to the `queued` event handler:

```
$(".upload").upload({
    autoUpload: false
}).on("queued.upload", onQueue);

function onQueue(e, files) {
    for (var i = 0, count = files.length; i < count; i++) {
        if (this !== that) {
            $(".upload").upload("cancel", files[i].index);
        }
    }
}
```

**Comment by ghost** [comment]
Thanks @benplum this is very helpful.
