### ISSUE TITLE
Single Page Navigation 

### ISSUE THREAD

**Issue by spartie17** [Formstone/Formstone#134]
Hi there!

I am hoping to use your slide-out navigation on my one-page site, it works flawlessly, except once a link is selected the page scrolls to the appropriate place, but the navigation needs to be manually closed as the page doesn't reload. 

I have tried to implement this method to try and make the navigation automatically close once a link is selected, but so far no luck!

$( function() {
    $('a').navigation('close');
});

It's obviously a little more advanced than that, and I was hoping that you would be able to advise me on the best way to go about doing this.

Thanks in advance,

Jess

**Comment by benplum** [comment]
You should be able to use the `close` method, however you need to target the Navigation element not the links:

$(".main_nav").navigation("close");
