### ISSUE TITLE
Lightbox "close.lightbox" event not triggered

### ISSUE THREAD

**Issue by zachabernathy** [Formstone/Formstone#138]
First off, great set of components. Love them.

I noticed an issue working with v0.8.36 lightbox.js where the "open.lightbox" event was firing properly but the "close.lightbox" event was not. I traced it down to Line 371 - `$Window.trigger(Events.close);` - and moved it to Line 379 right after `if (Instance.isMobile) {...}` and it seems to work fine now.

Hope this helps.

**Comment by benplum** [comment]
Good catch, I think I've found the issue. In the close transition callback all namespaced events are being unbound, including any user bound events. I'll try to get a fix up soon.

**Comment by benplum** [comment]
Closed in 0.8.37.

**Comment by zachabernathy** [comment]
Confirmed fixed. Thanks!
