### ISSUE TITLE
Tabber bug on IE 11

### ISSUE THREAD

**Issue by kenleee** [Formstone/Formstone#14]
When you have 2 sets of tabs on a page in IE11.   You can perform this test on your own demo (http://formstone.it/components/tabs/)
1.   First click on tab from set one.
2.  Click on tab from set two. 

Result.  Set one has a highlighted tab with no content.    

Comment:  The DOM show that "active" gets stripped from content.  This only was found in IE 11 (possibly) other IEs?.    

BTW, I love your approach to coding.

**Comment by benplum** [comment]
I'll check this out shortly.

**Comment by benplum** [comment]
Found the issue. Based on the MDN list of events (https://developer.mozilla.org/en-US/docs/Web/Events) I incorrectly assumed "activate" and "deactivate" would make good custom event namespaces. Apparently IE has a ton of other proprietary events it fires (http://help.dottoro.com/ljfvvdnm.php). There is now a check to make sure the event fired is the proper internal event, not the default that IE fires.

**Comment by kenleee** [comment]
Very awesome!   It's tested and working on my clients intranet.
