### ISSUE TITLE
Lightbox calculation issue

### ISSUE THREAD

**Issue by cspicuzza** [Formstone/Formstone#140]
I'm having an issue where the Lightbox is calculating some strange aspect ratios when the viewport is above 1400px.   

This is how it's displaying:  http://i.imgur.com/0wIVwKX.png

I'm using the latest version of Formstone and my style modifications are on a separate css file and none of the properties are targeting the image or container.

**Comment by cspicuzza** [comment]
I managed to fix this with

```
.fs-lightbox-image {
    display: block;
    max-width: 98vw;
    max-height: 90vh;
}
```

**Comment by benplum** [comment]
Can you send a link to the page? I'm curious to see why the max height/widths were needed.
