### ISSUE TITLE
Lightbox thumbnails?

### ISSUE THREAD

**Issue by scooterlord** [Formstone/Formstone#142]
Hello, I just came across this lovely set of components and have to say that I am really impressed about how well thought of they are; absolutely stunning work!

I was wondering, how easy would it be to implement a thumbnail gallery inside the lightbox?

Thanks in advance for your time!

**Comment by benplum** [comment]
It would be a pretty big undertaking to add this, but I will add it to the road map.

**Comment by scooterlord** [comment]
Thanks for taking this into account! :D Your mobile lightbox is one of the best I've seen, why not just make it the best there is?

**Comment by benplum** [comment]
Thumbnails will be landing in 1.1.0. Checkout the lightbox branch for a preview.

**Comment by benplum** [comment]
Added in 1.1.0.
