### ISSUE TITLE
Poster image does not unload when play() is called

### ISSUE THREAD

**Issue by simplethemes** [Formstone/Formstone#145]
In my example below, the poster image does not unload when play() is called.
I can hear the video playing but am unable to see it.

Am I doing something wrong here?
https://jsfiddle.net/sq49xo0L/1/

Thanks!

**Comment by simplethemes** [comment]
This seems to work, but seems a little dirty, no?
https://jsfiddle.net/3o2tcxn8/43/

**Comment by benplum** [comment]
This looks like a bug with the autoPlay option.

**Comment by benplum** [comment]
Fixed in 0.8.40. 

You still may want to use your second approach since the video will replace the poster once it's loaded, it's just won't play right away.
