### ISSUE TITLE
Upload doesn't work if same file select twice

### ISSUE THREAD

**Issue by EugeneFoo** [Formstone/Formstone#146]
Hi, if I select the same file and upload, the upload only fired on the first time while the second do nothing, unless i select another file to upload, then re-upload the  old files only works.

using demo also the same:  https://formstone.it/components/upload/

scenario: 
1. select file A upload, complete & display on screen.
2. select again file A upload, nothing functional.

is this a bug? or this behaviour force to be like this?

**Comment by benplum** [comment]
I can't replicate the problem, multiple uploads work for me. What browser are you using?

**Comment by EugeneFoo** [comment]
Hi Ben,

I'm using chrome. 
Windows version - Version 48.0.2564.116 m
Mac version - Version 48.0.2564.109 (64-bit)

Both unable to add, but I tried on FireFox it worked :/

**Comment by benplum** [comment]
Are you seeing any errors in the console?

**Comment by EugeneFoo** [comment]
Nope, nothing happened. If I change to upload another file then come back the old one, it will works.
Tested on 2 mac both same occurs on Chrome.

**Comment by EugeneFoo** [comment]
https://vid.me/E3hT - more detail demonstration. Drag drop same file multiple times is ok, only when select file via traditional popup filesystem method. Chrome browser.

**Comment by benplum** [comment]
Fixed in 0.8.40.
