### ISSUE TITLE
Zoomer - When will it be added?

### ISSUE THREAD

**Issue by sajpasa** [Formstone/Formstone#148]
Hi when will the zoomer be added to Formstone components?
Also in the current zoomer, is there anyway to get the image to fill the div and not have space left over on the top and bottom of the viewer div. 
Thanks

**Comment by benplum** [comment]
Hopefully sometime soon, there is another open ticket for Zoomer: https://github.com/Formstone/Formstone/issues/121

You should be able to play with the margin values to change the space above and below the image.

**Comment by sajpasa** [comment]
Hi, thanks for your input.
However no matter how much i play with margins, the images never seem to fill the `viewer zoomer-element` div. There is always remaining gaps, is it not possible get the image to fill 100% of the div.
The image below shows what i am getting.
<img width="725" alt="screen shot 2016-02-26 at 16 30 20" src="https://cloud.githubusercontent.com/assets/17335090/13358257/4b39ebd4-dca6-11e5-98f5-77c5a4424368.png">

Thank you for your help

**Comment by benplum** [comment]
I just tested this on the old demo user the console:

```
$(".zoomer_basic").zoomer("destroy").zoomer({ marginMin: 0 });
```

This will create an instance with no min-margin. It doesn't mean the image will always fill the entire parent, rather that the largest edge of the image will be flush with the corresponding edge of the parent.
