### ISSUE TITLE
Lightbox error on mobile

### ISSUE THREAD

**Issue by marvinengelmann** [Formstone/Formstone#15]
Formstone Classic - Boxer is working, but I can't get Lightbox working on mobile devices..

On tap the box opens and keeps showing the loading indicator.

The error in console is 

```
Uncaught TypeError: U.$content.touch is not a function
```

The site is build on bolt cms and I'm using the following bower components:

``` json
"jquery": "~2.1.4",
"formstone": "~0.5.11",
"normalize.css": "~3.0.3",
"font-awesome": "~4.3.0",
"pickadate": "~3.5.6",
"isotope": "~2.2.0",
"autosize": "~3.0.4",
"imagesloaded": "~3.1.8",
"jQuery.mmenu": "~5.1.2",
"slick.js": "~1.5.3"
```

**Comment by marvinengelmann** [comment]
Here the error with unminified js:

```
Uncaught TypeError: Instance.$content.touch is not a function (line 383)
```

in the section:

``` js
if (!Instance.visible && Instance.isMobile && Instance.gallery.active) {
    Instance.$content.touch({
        axis: "x",
        swipe: true
    }).on(Events.swipe, onSwipe);
}
```

**Comment by benplum** [comment]
Are you including the required dependencies? http://formstone.it/components/lightbox/#dependencies

core.js
touch.js

**Comment by marvinengelmann** [comment]
Oh, no I hadn't include it, there is only core.js and transition.js listed as dependencies. 

Sorry for my fail, now it works, thank you.

**Comment by benplum** [comment]
Updated the docs, sorry about that!
