### ISSUE TITLE
Checkbox inside lightbox

### ISSUE THREAD

**Issue by boiciuc** [Formstone/Formstone#150]
Hello, i`m using lightbox (inline content) for an login form that has an checkbox (with formstone checkbox applied on). Unfortunately once the lightbox is open the checkbox does not work (i`m assuming the content inside lightbox is just a clone of the inline content). I`m not sure this is a bug, but maybe there is a solution and i don`t see it :)

Thanks in advance for your time.

**Comment by benplum** [comment]
Can you provide an example we can check out? (jsbin, codepen, etc)

**Comment by boiciuc** [comment]
@benplum you can check it here: http://codepen.io/anon/pen/zqKwEj

**Comment by benplum** [comment]
Thanks! Fixed in 0.8.41.
