### ISSUE TITLE
Touch is a dependency for Dropdown

### ISSUE THREAD

**Issue by jameschambers** [Formstone/Formstone#153]
Just a heads up, the docs don't indicate that touch is a dep for the dropdown component, but it's required: 

https://formstone.it/components/dropdown/#use

**Comment by benplum** [comment]
It's only a dependency if you also include scrollbar. Scrollbar is actually an optional enhancement, but this could be more clear.

**Comment by jameschambers** [comment]
Ah, right you are! Love using Formstone btw, keep up the good work!
