### ISSUE TITLE
Synchronous XMLHttpRequest

### ISSUE THREAD

**Issue by ufhy** [Formstone/Formstone#155]
this is my code:

```
$.asap({
        selector: '.is-ajax',
        cache: false,
    });
```

I get warning message in console

```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
```

I dont know, how this happen??

**Comment by benplum** [comment]
Does your returned html contain a link or script tag? You should only be returning HTML, since all resources should be available from the initial page load. This thread has a little more info on the issue:

http://stackoverflow.com/a/33145617/2612062
