### ISSUE TITLE
Question about license

### ISSUE THREAD

**Issue by ghost** [Formstone/Formstone#156]
The change in license for commercial applications is in effect beginning v 1.0 or does it also applies if any older version is used? Also do you have an estimate of license cost for commercial use? Will you also offer component based licensing?

**Comment by benplum** [comment]
This will only affect projects using new releases, it does not change the license for older versions of the project. You can continue to checkout the 0.8.x branch, and we'll be supporting bugs in the 0.8.x branch through the end of August 2016 to give developers a chance to upgrade. 

Formstone will continue to be available for all open source projects under the GNU GPL v3.

Commercial licenses will be available tomorrow (March 21, 2016) on [UpLabs](http://www.uplabs.com/). The Single license will cost $50 and allow use on 1 commercial project. The Extended license will cost $200 and allow use on an unlimited number of commercial projects. We'll be running an introductory discount the first few weeks to help make the transition more manageable. 

We know this is a big change for our users, but believe it will help ensure the project continues to grow.

**Comment by benplum** [comment]
Pricing has been announced: http://formstone.it
Purchase on UpLabs: http://www.uplabs.com/posts/formstone
