### ISSUE TITLE
error with $Locks in the navigation module

### ISSUE THREAD

**Issue by agouticreative** [Formstone/Formstone#157]
Hi! I really like Formstone. I did some shopping around after jQuery Mobile turned out to be a bit of a bear when used with requirejs, and I settled here.
I ran into a error while using the Navigation module. I wanted to ask about it:
There is a local `$Locks` variable set to **null** in the module. It is defined _after_ the Plugin is initialized.
_Before_ the plugin is initialized and `$Locks` is defined, a function called `setup()` is created. It is passed into the plugin initializer. all it does is set value of that local `$Locks` variable to a JQuery collection of elements to "freeze" if appropriate (html and body, in this case:)
`function setup() {
        $Locks = $("html, body");
    }`
`$Locks` is then used in  `addLocks()` and `clearLocks()`, also as a local variable and not as a function argument, to add and clear the lock when appropriate.
Now, I was getting this error on line 273 of navigation.js, which is `addLocks()`, when triggering the open event on the nav element
**Uncaught TypeError: Cannot read property 'addClass' of null**
It was turning out that `$Locks` had the value of **undefined** in the context of `addLocks()` and `clearLocks()`.
I did a little digging and I saw that `$Locks` did not yet exist when `setup()` was run by the initializer.
Which makes sense, since the definition of `$Locks` comes after the initializing.
Is there any reason not to move the definition of `$Locks` to before the initializing of this plugin? I'm kind of unclear how this would ever have worked, but my implementation may be erroneous or may be introducing some kind of scope issue I don't understand.
Thanks!

**Comment by benplum** [comment]
Can you provide an example of this behaviour? The open event shouldn't trigger if the plugin isn't initialized, but maybe I mis-reading the issue.

**Comment by agouticreative** [comment]
Let me see about constructing an example. I'll close the ticket until then because this is pretty abstract.
but in the meantime, to your point...
the open (and close) events are triggering when they should.
But when they do, they are working with a `$Locks` variable that had to be scoped to the module when `setup()` tried to give it a value. `setup()`, `addLocks()` and `clearLocks()` all rely on the existence of a `$Locks` that is scoped to the module.
`setup()` takes a reference to that variable into the plugin constructor and defines its value there at construction time. If I move the declaration of `$Locks` above the construction of the plugin, it is scoped right when `setup()` executes, and the event functions can use it. But if it's defined after the plugin constructor, `$Locks` in `setup()` just amounts to a local variable in that function and `$Locks` in the module never gets a value.
