### ISSUE TITLE
Add type definitions to DefinitelyTyped

### ISSUE THREAD

**Issue by Bonscho** [Formstone/Formstone#159]
Just a suggestion: It would be helpful having type definitions available on https://github.com/DefinitelyTyped/DefinitelyTyped to be used for code completion and code inspection by some IDEs.

**Comment by benplum** [comment]
I'll have a look. Should be easy enough to add.

**Comment by IsaiahByDayah** [comment]
Has there been any new progress on this? I tried looking for Formstone typings but haven't found anything and was gonna make an issue until I saw this. Would love to use Formstone but with our workflow we need typings for it :/

**Comment by dnwhte** [comment]
+1

**Comment by Bonscho** [comment]
Maybe an addition to the [Google Closure Compiler](https://github.com/google/closure-compiler/tree/master/contrib/externs) would be helpful too.

**Comment by benplum** [comment]
We don't have the bandwidth to tackle this right now, but are absolutely open to a pull request!
