### ISSUE TITLE
Making tooltip fixed width

### ISSUE THREAD

**Issue by ghost** [Formstone/Formstone#16]
Hello guys!

Thank you for offering a good combination of components!

I'd like to use a tooltip with a large amount of text. Is there any way to make it fixed sized instead of spreading to all the width of the page (it goes over the page borders)?

Sincerely.
Kate

**Comment by benplum** [comment]
Yes, you will need to add a custom class and few lines of CSS:

```
$(".tooltip").tooltip({
    customClass: "long_text"
});
```

```
.long_text .fs-tooltip-content { 
    width: 250px; 
    white-space: normal; 
}
```

customClass was added in 0.5.12.

**Comment by ghost** [comment]
Thank you so much, Ben, for your reply!

-- 
Kate An
Sent with Airmail
