### ISSUE TITLE
Number: labels.up and labels.down issue

### ISSUE THREAD

**Issue by daniellelecomte** [Formstone/Formstone#160]
HI there,

I am not able to get the labels.up and labels.down options to work on the Number plugin. 

Have added the following to my input:

`data-number-options='{"labels.up":"More","labels.down":"Less","theme":"","customClass":"whatever"}'`

yet, only the theme and custom class options are recognized.

Am I missing something else here?

Thanks!

**Comment by benplum** [comment]
The `labels` option requires a multi-dimensional object (`.up` and `.down` are keyed off of a single `labels` option):

`data-number-options='{"labels":{"up":"More","down":"Less"},"theme":"","customClass":"whatever"}'`

There is probably be a better way to document this and we're open to suggestions!

**Comment by daniellelecomte** [comment]
Thank you!
