### ISSUE TITLE
enhancement request chunked uploads and datagrid

### ISSUE THREAD

**Issue by quasiperfect** [Formstone/Formstone#168]
hi

great work. i love Formstone
any plans to implement chunked uploads (http://www.plupload.com/docs/Chunking) and datagrid ( http://www.pontikis.net/labs/bs_grid/demo/ ) ?

**Comment by benplum** [comment]
Thanks for sharing these examples, they both look like great concepts we will be sure to explore in the future. Creating a better table has always been a challenge, especially on mobile devices and touch screens.

**Comment by ghost** [comment]
@benplum I'd love to see chunking specially in the style of resumable.js which is really awesome for large file uploads (100MB+ file sizes).

**Comment by benplum** [comment]
I'll check out resumable.js.

**Comment by benplum** [comment]
Just pushed a version with chunked uploads to the dev branch: https://beta.formstone.it/components/upload.html

It's been tested with everything from small jpegs to 500+ mb video files. We would love any feedback!

**Comment by benplum** [comment]
Milestone for chunked uploads. Starting a new issue for data grids.

**Comment by benplum** [comment]
This is ready to go and will ship with the next release.
