### ISSUE TITLE
Upload component breaks responsive design

### ISSUE THREAD

**Issue by ghost** [Formstone/Formstone#169]
Upload component whenever presents in a page introduces horizontal scrollbar. Here is from the demo page.

<img width="1492" alt="screen shot 2016-05-15 at 8 06 44 am" src="https://cloud.githubusercontent.com/assets/2308115/15274963/3d66fba8-1a74-11e6-867a-bbf214a18735.png">

**Comment by benplum** [comment]
This is fixed in 1.1.3.
