### ISSUE TITLE
Dropdown don't work in mobile Samsung S7562 default browser!

### ISSUE THREAD

**Issue by NabiKAZ** [Formstone/Formstone#171]
Dropdown don't work and not clickable in mobile Samsung S7562 default browser!

**Comment by benplum** [comment]
Any more info on this?

**Comment by NabiKAZ** [comment]
It's my device: http://www.gsmarena.com/samsung_galaxy_s_duos_s7562-4883.php

I use default browser on it.

When I click on "Option One" into drop down nothing happen!
But when enable "Desktop view" works well.

![screenshot_2016-06-09-12-18-54](https://cloud.githubusercontent.com/assets/246721/15922487/1df638b0-2e3d-11e6-9747-847555a2d26a.png)

![screenshot_2016-06-09-12-20-04](https://cloud.githubusercontent.com/assets/246721/15922510/4e1cb47e-2e3d-11e6-91ec-f8dc3134ca9c.png)

**Comment by benplum** [comment]
The closest thing I have to test with is a Galaxy S3, and the Dropdowns are opening the native options overlay as it should: 

![screenshot_2016-06-17-09-42-51](https://cloud.githubusercontent.com/assets/1130075/16152478/16bad8ce-3470-11e6-9310-7e022a3a856c.png)

I also have access to the S6, and it's stock browser behaves the same. Can you try remote debugging, or a mobile console (https://github.com/B1naryStudio/js-mobile-console), and report back any JS errors?

**Comment by benplum** [comment]
I'm closing this since it's an issue on a 4 year old phone's stock browser. Feel free to reopen if you can provide some more details.

**Comment by felicianuniversity** [comment]
Hi,  The dropdown still does not work on any mobile device.  I  tried to look at the demos and they dont expand on click either.  Can you help with getting this working?  Thanks!

**Comment by benplum** [comment]
Please open a new issue and provide more info on your problem.

**Comment by felicianuniversity** [comment]
Thanks will do!

**Comment by felicianuniversity** [comment]
Thanks!  Just opened ticket.

Ill stand by for a response.

Thanks again!!!!!
