### ISSUE TITLE
npm install formstone error

### ISSUE THREAD

**Issue by liu-dongyu** [Formstone/Formstone#173]
formstone@1.0.4 postinstall /home/ldy/company-project/liveneeq-webview/node_modules/formstone
 node ./node_modules/bower/bin/bower install

module.js:327
    throw err;
    ^

Error: Cannot find module '/home/ldy/company-project/liveneeq-webview/node_modules/formstone/node_modules/bower/bin/bower'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
npm ERR! Linux 3.16.0-71-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "formstone"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE

npm ERR! formstone@1.0.4 postinstall: `node ./node_modules/bower/bin/bower install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the formstone@1.0.4 postinstall script 'node ./node_modules/bower/bin/bower install'.
npm ERR! This is most likely a problem with the formstone package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/bower/bin/bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs formstone
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls formstone
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ldy/company-project/liveneeq-webview/npm-debug.log

**Comment by benplum** [comment]
Any more info here? Found a few similar issues in other projects.

https://github.com/linnovate/mean/issues/230
https://github.com/linnovate/mean/issues/43#issuecomment-219672560

**Comment by letoss** [comment]
Why is this closed? I have the same problem and the links above didn't help me to solve it.

Could you please write how to fix this problem? I really want to use this lib.
