### ISSUE TITLE
Carousel not moving past three slides and sometimes not loading

### ISSUE THREAD

**Issue by nickngqs** [Formstone/Formstone#174]
Somehow, I'm getting consistency problems loading the carousel for my pages. When going page to page, some pages are successful, some pages have this error.

![ss](https://cloud.githubusercontent.com/assets/3901903/15985938/d7bad920-302e-11e6-9eb2-ec0a04d5dc0d.png)

somehow this only affects webkit browsers - Chrome and Safari. Firefox doesn't seem to have this problem at all.

**Comment by benplum** [comment]
Can you share a link to the issue?

**Comment by benplum** [comment]
I'm having a hard time replicating this. A codepen or jsbin example would be really helpful.

**Comment by nickngqs** [comment]
Hi there!

I've solved the issue. Apparently I've to put the `<img>` inside of a `<div>`.
By doing so, it will work for Chrome and Safari. However, it's weird because the slider works in Firefox without the div tag.

I just got confused by the documentation assuming that the slider will reference all direct childs.
`Carousel will treat immediate children as items to scroll through`

**Comment by benplum** [comment]
Can you post a code sample? If your markup looks something like this Carousel should treat each `<div>` as a carousel item:

```
<div class="carousel">
    <div>
        <img src="image.jpg" alt="">
    </div>
    <div>
        <img src="image.jpg" alt="">
    </div>
    <div>
        <img src="image.jpg" alt="">
    </div>
</div>
```

**Comment by nickngqs** [comment]
### Initial Problem

```
<div class="carousel">
    <img src="image.jpg" alt="">
    <img src="image.jpg" alt="">
    <img src="image.jpg" alt="">
</div>
```

Doing this will not work on Chrome and Safari. But will work on Firefox. 
For the case in Chrome and Safari, sometimes the slider initialize, sometimes it doesn't.

<hr>

### Solution

```
<div class="carousel">
    <div>
        <img src="image.jpg" alt="">
    </div>
    <div>
        <img src="image.jpg" alt="">
    </div>
    <div>
        <img src="image.jpg" alt="">
    </div>
</div>
```

Doing this will work on all browsers.
