### ISSUE TITLE
Documentation of custom controls not clear enough

### ISSUE THREAD

**Issue by tpinne** [Formstone/Formstone#175]
The docs for the custom controls are not clear enough about the selectors to provide for the next and prev items. Because there has to be a container selector I would have thought that the next and prev selectors will be used only inside the given container. But in fact they have to be "fully qualified".

The problem which occurred to me has been two carousels with custom controls on the same page, each specifying a container selector and `.next` and `.prev` selectors. That led to controlling every carousel on that page with every control element.

To circumvent that I had to give the control container an ID and using the ID also in the next and prev selectors.

Either update the docs to make that a little bit clearer or make the next and prev selectors dependent on the container selector. Which I would prefer personally.

**Comment by benplum** [comment]
All three options require a fully qualified selector so the controls can be placed anywhere in the document (or there could be multiple sets of controls for the same Carousel). The container selector isn't actually required, only next and previous. The container selector simply adds sugar for styling both controls at once when changing the hidden/visible state. 

The docs could certainly be updated to add clarity to these options.
