### ISSUE TITLE
Enhancement - Pagination disabled classing

### ISSUE THREAD

**Issue by nhall** [Formstone/Formstone#176]
This would be an enhancement. What do you think about adding disabled classing to the previous and next controls when you are on the first and last pages?

**Comment by benplum** [comment]
This would be an excellent addition, we should be able to get this in the next release.

**Comment by benplum** [comment]
I just thought about this again, and the controls for the Carousel receive a `fs-carousel-visible` class when they are "enabled", I think we'll continue this pattern. Something like `fs-pagination-visible`, that way you can set base style for the invisible/disable state, then override when the control is visible/enabled.

**Comment by benplum** [comment]
This is up on the dev branch and will go live with 1.2.0
