### ISSUE TITLE
Enhancement - Carousel pagination allow for boolean or object

### ISSUE THREAD

**Issue by nhall** [Formstone/Formstone#177]
I'm not sure if this is necessary but what do you think of treating the pagination like the controls. Not only can you draw or not draw them but also define an object where you would like to draw them. This came up because there are many times where we want to display pagination at the top of carousels. Normally we just position absolutely. What do you think?

**Comment by benplum** [comment]
Makes total sense to me, we should be able to get this in the next release.

**Comment by benplum** [comment]
This is up on the dev branch and will go live with 1.2.0.
