### ISSUE TITLE
carousel/lightbox load more images

### ISSUE THREAD

**Issue by doonmok** [Formstone/Formstone#178]
With the carousel, we have users adding up to 15 images to it and instead of loading all 15 when the page loads, I have it where it loads 4 images. If an end user interacts with the carousel, it will load the rest of the images. 
I have jquery/ajax .click function that checks if carousel gallery is more then 4 images, if it is, add the rest of the images. It is kind of working how I expect it to except for lightbox, it is still saying 4 images in the pagination instead of 15 when I click on an image. Lightbox is being called before my jquery/ajax .click can be run. After I exit out of lightbox and click another image, it will have the 15 images. 
How would I stop lightbox from running before adding more images through my .click event? 

Here is my .click 

`$('.media_gallery_cover_buttons, #photos').click(function() {

```
    if (<?php echo $galleryCount; ?> > 4) {

        var pageId = '<?php echo $bigtree["page"]["id"]; ?>' ;
        var gallery_id = '<?php echo $gallery_id; ?>' ; 

        $.ajax({
             url: "/ajax/full-width-photo-gallery-two-full/",
                     type: 'get',
                    dataType:'html',
                     data: {id: pageId, galleryId: gallery_id},
                    success: function(data)
            {
                $('.fs-carousel-canister').append(data);
            },
           error: function(xhr, status, error) {
            alert(error);
         }
        })
    };  
});`
```

**Comment by benplum** [comment]
In your success callback, you will need to reinitialize the lightbox for the new elements:

```
$(".fs-carousel-canister .js-lightbox").lightbox();
```

You also will probably need to reset the carousel:

```
$(".js-carousel").carousel("reset");
```

Be careful with your `append` call. If there are multiple carousels on the page that code will append the ajax results to all of them.

**Comment by doonmok** [comment]
I had to use .mousedown instead of .click for the images to load before lightbox was called. Here is my code, cleaned it up a little bit too.

`$('.media_gallery_cover_buttons, .media_gallery_full_link, .fs-lightbox-control').mousedown(loadAllGallery);

```
function loadAllGallery() {

    var galleryCountLoaded = $('.media_gallery_full_link').length;
    var galleryCount = <?php echo $galleryCount; ?> ;

        if (galleryCount != galleryCountLoaded) {

            if (galleryCount > 3) {

                var pageId = '<?php echo $bigtree["page"]["id"]; ?>' ;
                var gallery_id = '<?php echo $gallery_id; ?>' ; 


                $.ajax({
                     url: "/ajax/full-width-photo-gallery-two-full/",   
                             type: 'get',
                            dataType:'html',
                            data: {id: pageId, galleryId: gallery_id},
                            success: function(data)
                    {
                        // alert(data);                     
                        $('.fs-carousel-canister').append(data);
                        $('.js-carousel').carousel('reset');
                    },
                 error: function(xhr, status, error) {
                    alert(error);
                 }

            })  
        };  

    };

}`
```
