### ISSUE TITLE
Carousel: Getting data from current/active slide

### ISSUE THREAD

**Issue by fowlercraig** [Formstone/Formstone#179]
Hey there, I'm trying to execute a function based on the classes of an active slide. I'm hoping to do something like this: 

```
if( $activeSlide.hasClass('dark') ) {
  $('.header').addClass('dark');
}
```

Is this possible? I haven't been able to find any mention of current or active slides in the documentation.

**Comment by benplum** [comment]
You can access the visible (or 'active') item with the `fs-carousel-visible` class:

```
$(".carousel").on("update.carousel", function() {
    if ($(".carousel").find(".fs-carousel-visible").hasClass("dark")) {
        // ...
    }
});
```

**Comment by fowlercraig** [comment]
Perfect. Thank you.
