### ISSUE TITLE
Lightbox gallery browsing doesn't work with IE9

### ISSUE THREAD

**Issue by mpaulasaari** [Formstone/Formstone#18]
Not sure if IE9 is even officially supported by Formstone, but we noticed that the Lightbox gallery doesn't function correctly with IE9. The first image opens fine and everything looks as expected, but as we tried to browse other photos from same gallery by clicking the left or right arrow it gets stuck. The lightbox shows the loading icon but second image is never loaded. You can replicate this at the demo site http://formstone.it/components/lightbox/

IE10 and IE11 seems to work correctly.

**Comment by benplum** [comment]
This is a bug and will be addressed soon.
