### ISSUE TITLE
Components render in default way at first in Chrome

### ISSUE THREAD

**Issue by pavelknotek** [Formstone/Formstone#180]
If I have a script tag at the bottom of a page (even empty script tag), components are rendering slowly in Chrome 51. Components display in their default way and after that they change the look. If there is no script tag after components everything is OK. I discovered this when using checkbox. You can reproduce the issue in your demo here on GitHub if you add `<script type="text/javascript"></script>` just before closing BODY tag to demo\components\checkbox.html. Please see attached screenshot.
![fs_cbx_issue](https://cloud.githubusercontent.com/assets/20361223/16698831/a9d34f7e-4550-11e6-82ee-6a4c947bad22.png)

**Comment by benplum** [comment]
This is certainly observable, but probably has more to do with how chrome parses, interprets, and compiles inline javascript. The inline script tag may be delaying when the document.ready is triggered, however the same behavior occurs if you move the demo site's script tag from the head to the footer. Looking at the timeline view in chrome, the inline script seems to pause the render for a "long frame". Other browsers (even Safari) do not exhibit this same behavior.
