### ISSUE TITLE
Issue with Http calls from upload component

### ISSUE THREAD

**Issue by ghost** [Formstone/Formstone#181]
I am building a web-app that uses upload (open source version) component. This web-app allows adding large files (up to 30 MB) from upload drag and drop. Sometimes I see this issue that if I add a bunch of files, upload component stops making http call in the backend after first or second file. I haven't been able to figure out the exact scenario when it happens. 

FYI the max file size supported in the app is 50 MB and I only allow one upload at a time even if multiple files are added in the queue.

The reason for opening this ticket is to see if anyone else is also facing this same issue.

**Comment by benplum** [comment]
Is the server timing out with the upload or is the connection resetting? Chunked uploads are certainly something we plan to implement in a future release.

**Comment by benplum** [comment]
I just commented on the other open issue, but the dev branch have a version of chunked uploads. Any and all feedback is welcome.

**Comment by benplum** [comment]
This is ready to go and will ship with the next release.
