### ISSUE TITLE
Allow nonInteraction on scrollDepth

### ISSUE THREAD

**Issue by Infthitbox** [Formstone/Formstone#182]
The scrollDepth tracking in the analytics component does not allow the nonInteraction option to be set. The major consequence of this is on bounce rate tracking, as any scroll event will count as not a bounce, which leads to wildly inaccurate bounce rate tracking (at least compared to bounce rate tracking without scrollDepth tracking). 

I would go so far as to argue that nonInteraction on scrollDepth should be the default.

**Comment by benplum** [comment]
I would agree.

**Comment by benplum** [comment]
So non-interaction is actually set to true for scroll depth events. You shouldn't see any difference in your analytics as a result. Do you have another event that could be triggering the interaction hit?

**Comment by Infthitbox** [comment]
Should have checked versions first; looks like this was fixed in December and we haven't updated in that time frame.

**Comment by benplum** [comment]
No worries, I do think be able to pass custom data to the scroll depth events would be a nice enhancement.
