### ISSUE TITLE
Carousel controller issue. 

### ISSUE THREAD

**Issue by fowlercraig** [Formstone/Formstone#188]
For the life of me, I can't figure out how to get one carousel to control another, as you have in the demo on the carousel page. 

Is there something I'm missing that's preventing this from working? 
Here's the site I'm developing at the moment https://dameht.com/pages/home
The main carousel starts at line 309 and the controller carousel begins at line 439.

**Comment by benplum** [comment]
Hmm, looks like you're running a much older version (0.8.x). Linked Carousels were introduced in [version 1.1.0](https://github.com/Formstone/Formstone/blob/master/CHANGELOG.md#110).

**Comment by fowlercraig** [comment]
_forehead slap_

Thanks
