### ISSUE TITLE
Compatibility with asynchronous script loaders?

### ISSUE THREAD

**Issue by jools-r** [Formstone/Formstone#19]
I am having problems with the setup functions of widget modules not executing when asynchronously loading the js-files with [script.js](https://github.com/ded/script.js). I can instruct script.js to make the widget function only execute when its dependencies are ready but it looks like the asynchronous loading is causing the Document Ready section at the end of core.js not to execute.

Would it be possible to make the _setup method callable via `$.plugin("initialize");`(or similar) much like "defaults" and "destroy" already is, while setting the respective initialized flag to prevent re-initialization of dependencies where they are used by different modules?

**Comment by some-say** [comment]
+1

**Comment by benplum** [comment]
This is honestly an issue I rarely run into as I compile all JS to a single file. @some-say has provided an excellent solution which is available in 0.5.13.
