### ISSUE TITLE
CSS Effects

### ISSUE THREAD

**Issue by DKudleichuk** [Formstone/Formstone#190]
Hello!

Is it possible to add some CSS effects (e.g. Fade or Slide) for Tabs / Toggles elements on click? 

Thank you

**Comment by benplum** [comment]
You should be able to hook into the `.fs-tabs-content` and `.fs-tabs-active` class to apply effects:

```
.fs-tabs-content {
    opacity: 0;
    transition: opacity 0.25s linear;
}

.fs-tabs-content.fs-tabs-active {
    opacity: 1;
}
```
