### ISSUE TITLE
Serialize Dropdown

### ISSUE THREAD

**Issue by lamka02sk** [Formstone/Formstone#191]
Hi, I am trying to serialize form with Dropdown selects inside and it does not work. Is there any way to do this in JS?

**Comment by benplum** [comment]
Can you provide any details on your browser? Maybe a live example to inspect? The plugin wraps the standard `select` element, so forms should behave as expected.

**Comment by lamka02sk** [comment]
I am using Firefox 48, but it does not work in Chrome too.
Here is my code example, but I think there is everything OK:

<form method="post">
      <div class="form-input">
           <label class="input" for="language">Language</label>
           <select id="language">
               <option value="en" selected="">English</option>
               <option value="sk">Slovak</option>
         </select>
    </div>
</form>

... in browser code looks like:

<form method="post">
          <div class="form-input">
               <label tabindex="-1" class="input" for="language">Language</label>
               <div class="fs-dropdown fs-light" id="language-dropdown" tabindex="0" role="listbox" aria-haspopup="true" aria-live="polite" aria-labeledby="language-dropdown-selected">
                    <select tabindex="-1" class="fs-dropdown-element" id="language">
                         <option value="en" selected="">English</option>
                         <option value="sk">Slovak</option>
                    </select>
                    <button type="button" class="fs-dropdown-selected" id="language-dropdown-selected" tabindex="-1">English</button>
                    <div class="fs-dropdown-options">
                         <button type="button" class="fs-dropdown-item fs-dropdown-item_selected" data-value="en" role="option" "aria-selected"="true">English</button>
                         <button type="button" class="fs-dropdown-item" data-value="sk" role="option">Slovak</button>
                    </div>
               </div>
           </div>
     </form>

In code everything seems to be fine, plugin works fine too while you don't try to use jQuery's serialize function - returns nothing.

To get this work (not the right way, but it is working), I created my own function, which takes data directly from Dropdown generated HTML, but still I want to know, where is the problem.

**Comment by benplum** [comment]
You need to set a `name` attribute on the select element for it to serialize. Here's an example of both, you'll notice only the named element outputs a value: https://output.jsbin.com/wolidel/
