### ISSUE TITLE
Enhancement request - Carousel tabbing

### ISSUE THREAD

**Issue by nhall** [Formstone/Formstone#194]
I've been thinking about how the carousels work with keyboard navigation. I've run into situations where carousel items contain links. If you are using your keyboard to tab through a document you can focus on links of inactive carousel items, this can cause some very weird layout scenarios when carousels are both contained and bleed off the page. What do you think of jumping to a carousel item when a child element has focus? I'm thinking something like this:

```
$target.find(".fs-carousel-item_next a, .fs-carousel-item_previous a")
  .on("focus", function () {
    var index = $(this).closest(".fs-carousel-item").index();
    $(this).closest(".js-carousel").carousel("jump", index);
});
```

I tested this out and it only really works if you are only showing one item at time. Otherwise the index of the parent item with focus won't be the value you want to jump to. For example, let's saw you are showing two at a time and you set focus to a link in the third item.  That would jump you to the third group of two, not the group of two containing the third item.  Confusing to type out.

I guess ideally this would be for any element that can be focused not just links. I don't know of a jQuery selector for this. I'd hate to have to list them all out: `a`, `input`, `select`, `textarea`, `buttons`, `object`, anything with a `tabindex` attribute...

Let me know what you think.

**Comment by benplum** [comment]
I think this would be a solid enhancement. We should be able to figure out what 'page' the focused element belongs to and jump to the proper position.

**Comment by benplum** [comment]
This is going to make it in to the next release. The carousel will scroll when tabbing to elements inside of a carousel item (or the item itself, if focusable). You can view it in action on the beta demos, the "Links" demo has some focusable elements as items: https://beta.formstone.it/components/carousel.html
