### ISSUE TITLE
Lightboxes with iFrames disappear when inputs are selected (mobile)

### ISSUE THREAD

**Issue by sashtown** [Formstone/Formstone#196]
Hey there! Tried to load some other page via iFrame in a lightbox. This page basically contains a quite simple form with inputs and selects. Works like a charm until I try to select one of the inputs or selects of the form on mobile. When doing that the lightbox disappears. Happens on iPad/iPhone with Mobile Safari and Chrome (latest iOS and browser versions).

In doubt of my own code I finally decided to simply download your demo, changed the iframe example url (nasa.gov) to a random one which also contains a(nother) form. And the same things are happening there.

Would be great to hear/read your thoughts on this. Thx in advance.

**Comment by benplum** [comment]
Is the lightbox closing or simply disappearing visually? I'll check this out, but don't have an immediate answer.

**Comment by sashtown** [comment]
It's disappearing visually and coming back when some input is made.
