### ISSUE TITLE
Combine Carousel and Lightbox

### ISSUE THREAD

**Issue by ursbraem** [Formstone/Formstone#198]
Hi Ben! Do you have experiences combining the carousel and the lightbox? All responsive and touch-enabled, of course... I've been looking for such a thing for so long and can't find an integrated solution.

The idea is that you have a carousel, and when the user clicks or taps into the center area of an image, the same carousel opens large, in a lightbox, with the clicked image selected.

**Comment by benplum** [comment]
You should be able to achieve this by combining the two plugins:

```
<div class="js-carousel">
    <a href="large-01.jpg" class="js-lightbox" data-gallery="gallery-01">
        <img src="thumb-01.jpg" alt="">
    </a>
    <a href="large-02.jpg" class="js-lightbox" data-gallery="gallery-01">
        <img src="thumb-02.jpg" alt="">
    </a>
    ...
</div>
```

```
$(".js-carousel").carousel();
$(".js-lightbox").lightbox();
```

The lightbox should open to the selected image in the gallery, assuming a matching `data-gallery` attribute exists on all links in the carousel. 

We published a live example in a blog post a while back: https://formstone.it/blog/5-minute-media-gallery-with-carousel-and-lightbox/

**Comment by ursbraem** [comment]
Oh, thanks a lot! I hadn't seen that and google would stay silent for "carousel lightbox jquery plugin..." Though, I've implemented a solution with photoswipe and owl in the meantime. But I'll keep it in mind for the next time!
