### ISSUE TITLE
Background fails to trigger loaded event on cached images

### ISSUE THREAD

**Issue by timbuckingham** [Formstone/Formstone#199]
Line 309 of https://github.com/Formstone/Formstone/blob/dev/src/js/background.js

Triggers Events.load rather than Events.loaded

**Comment by benplum** [comment]
That's for the internal image `load` event on [line 277](https://github.com/Formstone/Formstone/blob/dev/src/js/background.js#L277).  The `loaded` event should fire once the image has loaded, on [line 296](https://github.com/Formstone/Formstone/blob/dev/src/js/background.js#L296).

**Comment by timbuckingham** [comment]
Weird, you're right and my console logs show the "loaded.background" event being fired inside the load event but for cached images the event watcher on loaded.background never fires.

Something in the load event seems to be messing with the simple event watcher:

```
$(".js-background").one("loaded.background", onLoad);
```

I tried manually calling $img.trigger(Events.loaded); after Events.load AND after Events.load and in both cases the event fails to hook properly.

I then completely dropped line 308 and it seems to be behaving properly -- the cached images appear to still be calling Events.load and the premature(?) call seems to do something crazy. Tested in Firefox/Safari/Chrome.

**Comment by timbuckingham** [comment]
Following up a little more, it appears that due to the main load event being $img.one the premature(?) firing on line 309 consumes that event and it somehow malfuctions. I don't see why the loaded event still wouldn't trigger but switching $img.one to $img.on and leaving line 309 makes it call properly as well.

**Comment by benplum** [comment]
Hmm, do you have a test case I can take a look at? The readyState check was initially for old IE compat, so I wonder if it's even necessary anymore.

**Comment by timbuckingham** [comment]
Unfortunately I don't have a link to any place it's not fixed by commenting out that line :| Ford's will probably panic if I break it again, hah! We did just encounter it again on another usage in Madeira but I believe that's in the process of being fixed as well. Strangely in that instance it worked fine in Chrome but failed in Firefox each time.

**Comment by benplum** [comment]
Cool, I'll see if I can track it down, just not seeing it on the demos.

**Comment by benplum** [comment]
Is the plugin being destroyed and rebuilt at any point? Plugins will unbind any events tied to the namespace during the [teardown cycle](https://github.com/Formstone/Formstone/blob/dev/src/js/background.js#L113). If so, you may need to rebind your `loaded.background` event listener after the plugin target has been re-initialized.

**Comment by timbuckingham** [comment]
It doesn't look like it -- the only other call to the background plugin is in a click event which loads a different image. We were also running into the same load issue with the Viewer plugin.

**Comment by benplum** [comment]
I've been scratching my head on this so I put together a quick code pen and can't replicate the issue: http://codepen.io/benplum/pen/vyxabN

The 'Loaded' text should be logged in the console whenever a background image is loaded. 

I also put one together for Viewer since you mentioned that having an issue as well: http://codepen.io/benplum/pen/ozmooJ

Are you experiencing different results?

**Comment by timbuckingham** [comment]
Sorry for the extraordinarily long response time, things have been crazy! Here's a live example of it being broken:

http://dev.fastspot.com/clients/buphx/

Hopefully you remember the login -- I can get it to happen every time in Firefox - after the initial background load of the second component it refuses to fire the event on the cached image.

**Comment by benplum** [comment]
Looks like there is an earlier background initialization in the page.js that would be causing the `loaded` event to fire before the event in topics.js is bound. I modified the code pen to reflect the different image sources and event bindings: http://codepen.io/benplum/pen/vyxabN You can view the different loaded events being triggered in the console.

**Comment by timbuckingham** [comment]
Thank you so much! We've been scratching our heads forever but dropping the double background initialization did the trick!

**Comment by benplum** [comment]
No prob 👍
