### ISSUE TITLE
Navigation bug in latest Chrome

### ISSUE THREAD

**Issue by ghost** [Formstone/Formstone#2]
I've uploaded a video to show the problem --> https://youtu.be/kePoKifvuCY

When you scroll the page after opening & closing the menu the sticky nav bar flickers. I've tested it in Safari and Firefox and it works fine, just seems to be Chrome having the issue.

**Comment by ghost** [comment]
The video is unavailable.Make it public.

**Comment by benplum** [comment]
I believe this is a Chrome bug introduced with the switch from webkit to blink. I don't always see it occur (on this or any other site running Navigation), and if you resize after opening/closing it typically clears the behavior.
