### ISSUE TITLE
Can't install Formstone through npm

### ISSUE THREAD

**Issue by azramahmutovic** [Formstone/Formstone#200]
After running npm install formstone I get the following error:
npm ERR! Linux 3.19.0-73-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "formstone"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! formstone@1.3.0 postinstall: `node ./node_modules/bower/bin/bower install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the formstone@1.3.0 postinstall script 'node ./node_modules/bower/bin/bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the formstone package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/bower/bin/bower install

**Comment by letoss** [comment]
I have the same problem.

**Comment by mackensen** [comment]
We're seeing this too. You can bypass the error by doing `npm install --ignore-scripts`, but if you have any other modules which have installation scripts those won't run and you'll have other problem.

**Comment by benplum** [comment]
This is fixed on the dev branch, we'll be pushing a new version soon.
