### ISSUE TITLE
Checkbox drawing two markers?

### ISSUE THREAD

**Issue by matthisamoto** [Formstone/Formstone#201]
Really strange thing happening, getting two fs-checkbox-markers drawn:

![screen shot 2016-12-08 at 1 54 53 pm](https://cloud.githubusercontent.com/assets/547172/21023365/2e86de5a-bd4e-11e6-8632-88ca90d31446.png)

Inspection showing a weird nested duplicate:

![screen shot 2016-12-08 at 1 55 22 pm](https://cloud.githubusercontent.com/assets/547172/21023366/32be0052-bd4e-11e6-9237-3e8bb9185fcb.png)

Markup only showing one radio input per piece:

![screen shot 2016-12-08 at 1 55 43 pm](https://cloud.githubusercontent.com/assets/547172/21023370/36c8a454-bd4e-11e6-8ee0-d81239db88ae.png)

**Comment by matthisamoto** [comment]
Okay so apparently the form was getting drawn twice without my knowing. Sorry for the dumb issue.

**Comment by yabdab** [comment]
I am having this same issue. How exactly was your form getting drawn twice?

**Comment by matthisamoto** [comment]
Hi @yabdab, unfortunately I don't really remember what the instance was in this particular issue, it was a little too long ago. I'd just make sure that you don't have two forms with the same id or name, however you are implementing .checkbox(). If you are calling checkbox twice for different object, make sure the selectors are different so that it won't attempt to invoke the function twice on the same object.

**Comment by yabdab** [comment]
Thanks for the reply. I went ahead and added `not('fs-checkbox-element') `when calling checkbox() so it would not fire twice.
