### ISSUE TITLE
No error function on lightbox

### ISSUE THREAD

**Issue by joonas-yoon** [Formstone/Formstone#202]
I got this error below when i using lightbox on AngularJs
```js
(lightbox:15) Uncaught TypeError: ca.$image.one(...).error is not a function(…)
```

i ~solved~ ignored this error, but evil trick :(
```js
...
ca.$image = ca.$imageContainer.find("img"),
ca.$image.one(W.load, function() {
    var a = O(ca.$image);
    ca.naturalHeight = a.naturalHeight,
    ca.naturalWidth = a.naturalWidth,
    ca.retina && (ca.naturalHeight /= 2,
    ca.naturalWidth /= 2),
    ca.$content.prepend(ca.$imageContainer),
    u(),
    k()
})
.error(N)  // i removed this
.attr("src", b).addClass(V.image),
...
```

i can not understand why it is not working and not defined error()

**Comment by benplum** [comment]
Looks like this is because the `.error` function was deprecated in jQuery 1.8, and removed in 3.0. We'll move to a `.on` style event binding, but you may need to use a different jQuery version for the time being.

**Comment by joonas-yoon** [comment]
Thanks !

**Comment by Bonscho** [comment]
Hi Ben. Do you have an idea when this issue will be solved? Just stumbled upon it on an urgent project.

**Comment by benplum** [comment]
This is fixed on the dev branch, we'll be pushing a new version soon.
