### ISSUE TITLE
maxQueue: 1 allowing multiples in Queue

### ISSUE THREAD

**Issue by JoshuaBedford** [Formstone/Formstone#203]
I'm testing the plugin to see if it's something I will use, but I've come across a few bugs (or maybe just odd situations). I'll paste my options below for your viewing. I have multiple set to false and maxQueue set to 1, as I only want the user uploading a single file. However, it allows the user to queue multiple files for upload still. And what's even stranger than that is, if multiple files are queued, and one is canceled, the others are then uploaded as the completed state activates. Perhaps it is user error, but this seems a rather strange thing to happen. As you will see, I have not changed anything with onComplete or onCancel, so this seems to be default behavior.

These are the options:
`$(".upload").upload({
	maxSize: 1073741824,
	beforeSend: onBeforeSend,		
	action: "{{ url('/application/resume/upload') }}",
	autoUpload: false,
	multiple: false,
	maxQueue: 1
}).on("start.upload", onStart)
.on("complete.upload", onComplete)
.on("filestart.upload", onFileStart)
.on("fileprogress.upload", onFileProgress)
.on("filecomplete.upload", onFileComplete)
.on("fileerror.upload", onFileError)
.on("chunkstart.upload", onChunkStart)
.on("chunkprogress.upload", onChunkProgress)
.on("chunkcomplete.upload", onChunkComplete)
.on("chunkerror.upload", onChunkError)
.on("queued.upload", onQueued);`

onBeforeSend included as it's called above:
`function onBeforeSend(formData, file) {
	console.log("Before Send");
    formData.append("_token", "{{ csrf_token() }}");
    formData.append("file_title", file.name);
	return formData;
}`

Why does canceling one file submit another? I can probably stop this behavior, but it seems strange that it would be a default behavior without auto upload enabled (basically enables auto upload for files in queue).

**Comment by benplum** [comment]
I think there may be some confusion on what the properties do, so perhaps they should be re-named. 

-`maxQueue` will control how many files will be uploaded simultaneously. This is pretty counterintuitive - something like `maxSimultaneous` to better indicate what it will control?
-`multiple` will allow the user to select multiple files from the OS dialog only (not how many can be dropped). This does not control how many files can be update in total. A new property (maybe `maxFiles`?) could be introduced to limit how many files in total can be uploaded. 

You could also hook into the various events or the `onBeforeSend` callback to modify the interface and disable the upload functionality after the first file has been uploaded.

**Comment by JoshuaBedford** [comment]
I like what you have presented @benplum. I have read the documentation and found out that maxQueue isn't what is originally seen, but the first thought (of apparently more than just me) is something different. Even adding a maxFiles option would be highly beneficial, as some places need a certain number of files. For example, handling one file is very different server side from handling 3.

The idea about using onBeforeSend is an interesting one, that after the first file is uploaded, then disable any further uploads. It isn't necessarily something that should have to be added though, because I'm sure others want the drag and drop capability for a single file (it is much more professional).

**Comment by benplum** [comment]
Closed in 1.3.1.
