### ISSUE TITLE
Scrollbar jumping in dropdown

### ISSUE THREAD

**Issue by libity** [Formstone/Formstone#206]
Hey,
if I scroll through a dropdown it jumps in the last moment to the end.
Especially if you scroll slowly you can see it.
Is there any way to fix this?

**Comment by benplum** [comment]
What browser(s) are you seeing it in? Can you share a codepen or jsbin of the issue?

**Comment by libity** [comment]
[codepen.io/anon/pen/ygOGww](http://codepen.io/anon/pen/ygOGww)
Using Firefox Version 50.1.0.
I have the Problem on the Demopage too: [https://formstone.it/components/dropdown/demo/](https://formstone.it/components/dropdown/demo/)
Just scroll down a list slowly and you will notice, that jump before you reach the end of the list.

**Comment by benplum** [comment]
Wow, yeah I'm seeing this on all Scrollbar demos in Firefox. We'll take a look and hopefully have a fix soon.

**Comment by libity** [comment]
Will you let me know as soon as the fix is finished?

Edit:
I have found an other problem:
If you drag the scrollbar handle and drop the cursor at it, the dropdown closes.

**Comment by benplum** [comment]
This has been fixed on the dev branch. You can preview the fix on the beta site: 

https://beta.formstone.it/components/dropdown.html
https://beta.formstone.it/components/scrollbar.html

We'll have a new release out soon that contains the recent updates.

**Comment by libity** [comment]
Yeah, it looks fine at the beta site.
But there is still the problem, that the dropdown closes, if you click on `.fs-scrollbar-handle`

**Comment by benplum** [comment]
Closed in 1.3.1.
