### ISSUE TITLE
Two another issues with Scrollbars

### ISSUE THREAD

**Issue by libity** [Formstone/Formstone#207]
I don't know if you have noticed my last comment, but I found two other problems with scrollbars on Firefox.
First: If you drag and drop the scrollbar handle on a dropdown menu, it closes, although you don't want to close it.
Second: You can't scroll with your mousewheel, if you hover on the scrollbar.

The official demopages are showing this issues too.
[https://beta.formstone.it/components/dropdown.html](https://beta.formstone.it/components/dropdown.html)
[https://formstone.it/components/scrollbar/demo/](https://formstone.it/components/scrollbar/demo/)

**Comment by benplum** [comment]
Thanks for reporting, we'll take a look.

**Comment by benplum** [comment]
Both of these should be resolved on the dev branch: https://beta.formstone.it/components/dropdown.html

The first required simply killing the click event on the Scrollbar handle. The second required mapping the `wheel` event from the custom track to the scrollable content area.

**Comment by benplum** [comment]
Closed in 1.3.1.
