### ISSUE TITLE
Resolve conflict on dropdown

### ISSUE THREAD

**Issue by TolotraRam** [Formstone/Formstone#208]
Hi,

Just want to know how to resolve the conflict with dropdown as it is the same as bootstrap initialisation, since i need both.

Cheers

**Comment by TolotraRam** [comment]
Oups, sorry find it but it should be in the doc that you can call fsDropdown.
Great job anyway.

**Comment by benplum** [comment]
We mention the NoConflict function in Core (https://formstone.it/components/core/) but this could be more clear. We'll add this to the list of updates.
