### ISSUE TITLE
Enabling dropdown on IE 11 with jquery 3.1.0

### ISSUE THREAD

**Issue by TolotraRam** [Formstone/Formstone#209]
Hi,
found a bug.
Enabling disabled dropdown doesn't work on internet explorer 11 and 10 when i use jquery 3.1.0, but it worked using jquery 2.

thanks

**Comment by benplum** [comment]
Thanks for reporting, we'll check this out.

**Comment by benplum** [comment]
Looks like this has to do with how the disabled state for an `option` is presented in IE when the parent `select` is disabled. We should have a fix on the `dev` branch shortly.

**Comment by benplum** [comment]
This is on the dev branch, should be released with 1.3.1. You can preview it here: http://codepen.io/benplum/pen/BpWaZV

**Comment by TolotraRam** [comment]
Thanks,
Seems to work well on codepen, waiting for release 1.3.1

Cheers,

**Comment by benplum** [comment]
Closed in 1.3.1.
