### ISSUE TITLE
Problem with size of lighbox.

### ISSUE THREAD

**Issue by TrangDinhVan** [Formstone/Formstone#210]
I have exactly same problem as https://github.com/Formstone/Formstone/issues/140
Please help.
We can see it we click on the product picture
http://nhahiendai.wpair.net/san-pham/woo-album-4.html

**Comment by benplum** [comment]
The problem is this CSS:

```
img,
iframe,
embed {
	max-width: 100%;
}
```

This style is overriding the inline image sizes Lightbox sets on the element.

**Comment by TrangDinhVan** [comment]
Could you please be more specific, because I searched back and ford without finding such that CSS rules in the site. I tried to add max-witdth: none !importabnt; to those elements, but not work.

**Comment by TrangDinhVan** [comment]
Ah, thanks for that, it's true.
