### ISSUE TITLE
Providing SASS Translations

### ISSUE THREAD

**Issue by benplum** [Formstone/Formstone#214]
This looks promising: https://www.npmjs.com/package/grunt-less-to-sass

**Comment by benplum** [comment]
@matthisamoto Finally got around to setting up a SASS translation branch: https://github.com/Formstone/Formstone/tree/sass

I'm sure there are going to be issues, but let me know if anything is working.

**Comment by matthisamoto** [comment]
This is sweet, I'm gonna try this out on the next project and see how it goes! Thanks for looking into it, I haven't had a chance to walk through any of that yet.
