### ISSUE TITLE
mediaquery.js: enter/leave differentiation in state object

### ISSUE THREAD

**Issue by matthisamoto** [Formstone/Formstone#215]
So I've noticed when you change screen sizes from one breakpoint to another, there seem to be two events firing. 

Looking through the code, it seems one would be an enter, entering a new breakpoint, and the other a leave, leaving the old breakpoint. Being able to differentiate between the two when listening to the event and using the state object would help cut down on calling functions twice, if we can pass that as an attribute of the object as event type or something?

Or perhaps I'm missing something?

**Comment by benplum** [comment]
You are correct, and this is sort of expected. I'm assuming you are initializing with both min and max width arrays. If you don't need one set (for instance, if only really care about minWidth for mobile first development) you can omit the max values to reduce the number of events that fire. When both sets of arrays are defined the plugin will set up listeners for both the `min-width` and `max-width` media query at the same point, which will then fire 2 events when the state changes.

**Comment by matthisamoto** [comment]
I think that's true in a one-off case. Trying to think about if there would be a case to need that. Maybe there isn't. At any rate, that'll help for what I'm trying to do.
