### ISSUE TITLE
<checkbox> will be moved prepend to <label> 

### ISSUE THREAD

**Issue by dukecroc** [Formstone/Formstone#219]
If a &lt;label&gt; has for="xxx" attribute, 
&lt;input type="checkbox" id="xxx"&gt; will be moved prepend to &lt;label for="xxx"&gt;.

Here is [Demo](https://codepen.io/dukecroc/pen/qmbgpq).

Can checkbox just stay original place?

**Comment by benplum** [comment]
This will be addressed in the next release.

**Comment by benplum** [comment]
Fixed in 1.4.0.
