### ISSUE TITLE
Cannot use keyboard on dropdowns

### ISSUE THREAD

**Issue by eigan** [Formstone/Formstone#22]
URL: http://formstone.it/components/dropdown/

The only thing I am missing here is the possibility for keyboard interaction. Using arrows when a dropdown have focus should let me navigate the list.

**Comment by benplum** [comment]
If you tab to a select, you should be able to navigate the list. What browser are you having trouble with?

**Comment by eigan** [comment]
In both Chrome and Firefox for Mac can I use the arrows up and down to navigate standard <select> elements. I cannot do that with this component. I dont know if this is a standard for <select> boxes in browsers, but having the same behavior would help for those who use keyboard to navigate.

I cannot use this library as it is right now because of this, but I could try to make a pull request if I end up using it :)

**Comment by benplum** [comment]
Do you mean once the drop down opions list is open?

**Comment by eigan** [comment]
Yes. To change the values selected in the dropdown.
