### ISSUE TITLE
[Carousel] Get carousel data through event: update.carousel

### ISSUE THREAD

**Issue by TrangDinhVan** [Formstone/Formstone#221]
Hello,
Is there any way to get carousel data through the event `update.carousel`?
For example, I wanna get the number of available items on next page, what is current page?,...
Thanks!

**Comment by benplum** [comment]
The `update` event currently passes the new index as an event parameter: 

```
function onUpdate(e, index) {
    ...
}
```

And you can fetch all instance data using jQuery's `data` method:

```
$(".carousel").data("fs-carousel");
```

You could combine these:

```
function onUpdate(e, index) {
    var carouselData = $(this).data('fs-carousel');
    ...
}
```

Do you need more specific data exposed?
