### ISSUE TITLE
Dropdown reset to default option?

### ISSUE THREAD

**Issue by baimurzin** [Formstone/Formstone#222]
Dropdown reset to default option?
How do I can reset or set manually an option? 

If I use simple way to set it like that: 
```
$('#my-select').val(0) // it's my select
//or 
$('#dropdown-selected').siblings('select').find('option').filter(function () {
     return $(this).val() == 0;
}).prop('selected', true);
```
That's not work. It's event doesn't change the text in selected option. And when I submit a form, it also submitted old value.

**Comment by benplum** [comment]
You'll need to trigger the change event after setting the value:

```
$('#my-select').val(0).trigger('change');
```
