### ISSUE TITLE
[upload.js] onfileabort event not pass the reason of the abort

### ISSUE THREAD

**Issue by zodman** [Formstone/Formstone#223]
i had small app what upload a image with upload.js the restriction is the filesize.

My backend server response status_code 400 and the json error. 

Upload.js not had the way for passing the json response on error.

i had fixed on this.. its not complete but it works

https://github.com/zodman/Formstone/commit/40ea406664966eac9cdc58a44b4261ccf346b67b

**Comment by benplum** [comment]
Thanks! We'll be exposing more AJAX params in the next release.

**Comment by benplum** [comment]
Fixed in 1.4.0.
