### ISSUE TITLE
about lightbox options

### ISSUE THREAD

**Issue by tsururu** [Formstone/Formstone#225]
hi!
Please tell me the correct answer.
and... I can not use English well. sorry....

If I add an option, an error will occur.
[ SyntaxError: missing : after property id ]

	<script src="js/core.js"></script>
	<script src="js/touch.js"></script>
	<script src="js/transition.js"></script>
	<script src="js/viewer.js"></script>
	<script src="js/lightbox.js"></script>
	<script>
	$(".js-lightbox").lightbox({
		thumbnails: true,
		labels.next: ">"    <--- add
	});
	</script>
</body>

why?

please tell me the correct answer.

I want to move like demo
[https://formstone.it/components/lightbox/demo/](url)
Like "thumbnail gallery" on this page

#####  add #####
	$(".js-lightbox").lightbox({
		"thumbnails":true,
		"labels.next": ">"
	});

There is no error, but it does not work.

**Comment by boiciuc** [comment]
The labels option requires a multi-dimensional object:

```
$(".js-lightbox").lightbox({
	"thumbnails":true,
	"labels": {
                     "next": ">"
         }
});
```

Should work just fine. @benplum mentioned in an old reply that he is open at proposals how to better document this :)

**Comment by tsururu** [comment]
hi.
Thank you very much.
it was worked.thanks a lot and best regards.

i have more question.

how to get a formstone lightbox tutorial and demo source.
i can't find it.

I want to move like demo
https://formstone.it/components/lightbox/demo/
Like "thumbnail gallery" on this page

please tell me about it.

thanks

**Comment by benplum** [comment]
The code example is on that page, simply set the `thumbnails` options to true:

```
$(".lightbox").lightbox({
	thumbnails: true
});
```

The plugin will handle the rest!
