### ISSUE TITLE
Dropdown opens with enter bug

### ISSUE THREAD

**Issue by libity** [Formstone/Formstone#226]
Hey,
I have found a bug. I use the dropdowns for a signup-form and if I focus an other input-element and push enter, it opens the dropdown.

https://codepen.io/anon/pen/awMBzg

Best regards
UV

**Comment by libity** [comment]
Will you release a new version with this fix soon?
Or should I fix it by hand? Then i should know how to fix it. ^^

**Comment by benplum** [comment]
I having trouble replicating this outside of your demo. Can you set up a demo with non modified scripts served from a CDN?

**Comment by libity** [comment]
I have to apologise.
It seems that the bug was caused by myself.
Sorry for that.
