### ISSUE TITLE
[Dropdown] CSS issue with Firefox

### ISSUE THREAD

**Issue by jdecool** [Formstone/Formstone#23]
I just test the dropdown component, but I have an graphic issue (you can see in the JSFiddle screenshot). The component opens from the top.

![jsfiddle](https://cloud.githubusercontent.com/assets/433926/7802460/1a634b9e-0336-11e5-9525-5cc220763635.png)

You can test my code at : http://jsfiddle.net/tcbnmn85/4/

My configuration : Ubuntu 15.04 with Firefox 38.0

Thanks your for work on these components.

**Comment by benplum** [comment]
This has to do with the height of the page. Dropdown tries to figure out if it's close to the bottom edge of the page and swaps it's display to compensate. I think you need to extend the height of the page with content or styles.

**Comment by jdecool** [comment]
You right ! Thanks for you answer.

But this is different of the native dropdown. Is it possible to make a fix for that ?

**Comment by benplum** [comment]
I don't believe so. HTML elements can't extend past the page like native OS elements can.
