### ISSUE TITLE
transforms on navigation-enabled interferes with fixed menu

### ISSUE THREAD

**Issue by mackensen** [Formstone/Formstone#231]
We have a somewhat unusual use case in that we're combining a mobile-friendly slide-out menu with fixed sidebar navigation. To ensure that the menu is always available we set `maxWidth: 10000px`. The `translate3d(0, 0, 0)` definitions on the navigation elements provoke the bug described here: https://stackoverflow.com/questions/36855473/position-fixed-not-working-is-working-like-absolute. Removing the translate3d styles resolves that issue and doesn't seem to have an impact on performance, but I was only testing "by eye" and can't speak for all devices.

**Comment by benplum** [comment]
Which `type ` are you using? The `transform` styles should only be added to content elements for `push` and `reveal`. This originally had to do with some browsers needing a starting property to transition from, but I'd be curious if it's still required. Do you have an example online we can take a look at?

**Comment by benplum** [comment]
Circling back on this one - the behavior described has to do with the [stacking context created by the transforms](https://stackoverflow.com/questions/15194313/transform3d-not-working-with-position-fixed-children). You can also override the classes to unset the `transform` properties.
