### ISSUE TITLE
Number: Rounding problems using step size lower than 1

### ISSUE THREAD

**Issue by Bonscho** [Formstone/Formstone#232]
Trying to avoid rounding issues by calculating a difference between the calculated value and a multiple of the step size as implemented in the step function only works stable for step sizes above 1 or for integer step sizes. 

Using a step size of `0.01` for example leads to no value change if the next higher step could not get reached because the calculated step size is lower than the configured step size. So the difference is substracted from the calculated step size and the result is a no change. 

I think handling rounding issues should be the browsers task. I would prefer to remove the `diff` calculation from the step function.

**Comment by Bonscho** [comment]
Thanks a lot!

**Comment by alexsorokoletov** [comment]
I got same issue with 1.4.0 and updating to 1.4.1 does not help. Tried both steps 0.01 and 0.1, entering 3 and getting 2.99 or 2.9 correspondingly.
