### ISSUE TITLE
Add option for background.js alt description

### ISSUE THREAD

**Issue by mimoduo** [Formstone/Formstone#233]
Having the ability to add an alt description to the background.js element would be great for accessibility.

Sincerely,
Bryan Stoner

**Comment by rjbain** [comment]
@benplum We're on an older version of Formstone, but would like to take advantage of this feature. Is it possible to upgrade only the background.js file without updating all of FS? I tried updating that file and it didn't seem to work. Thanks!

**Comment by benplum** [comment]
Depending on how old your version is you will probably need to update. You can also manually patch based on changes from [commit](https://github.com/Formstone/Formstone/commit/e7bdede115e113f1d912edc93004f7ec6fe9cbaa).

**Comment by rjbain** [comment]
Thanks, @benplum!
