### ISSUE TITLE
Use single class selectors, when possible, for all styles

### ISSUE THREAD

**Issue by mimoduo** [Formstone/Formstone#235]
This would make it easier to style down with overrides and hopefully easier to maintain. Plus all the unique selector work in the markup is already available.

Sincerely,
Bryan Stoner

**Comment by benplum** [comment]
Do you have specific examples? We've tried to keep compound selectors in areas where specificity matters.

**Comment by mimoduo** [comment]
Shoot, the more I look at the source, the more I can see where multiple classes are purposeful such as .enabled, .contained, or .ready. I think my concern comes more from extra theme styles that I've overwritten for each project like the lightbox backgrounds. I'll close this one for now! Thank you, Ben!

Sincerely,
Bryan Stoner
