### ISSUE TITLE
Typo in Grid?: cell helper class fs-[x]-justify-start

### ISSUE THREAD

**Issue by matthisamoto** [Formstone/Formstone#238]
The class for `fs-[x]-justify-start` on the cell reads `margin-left: right;` which errors out in-browser. 

![screen shot 2017-12-06 at 12 38 09 pm](https://user-images.githubusercontent.com/547172/33678762-5b885b2a-da82-11e7-9454-c6bf7b80b313.png)

I'm guessing this should say `margin-right: auto;` like `fs-[x]-justify-end` says `margin-left: auto;` ?

**Comment by benplum** [comment]
That is correct - just pushed a new version that fixes this. Thanks for the heads up!
