### ISSUE TITLE
Documentation Background (Wallpaper)

### ISSUE THREAD

**Issue by rriemann** [Formstone/Formstone#24]
I think there some important things missing in the background documentation.
- are videos auto-started on mobile platforms and if not, how can this be achieved
- is there an api to know if a video is currently played or paused

**Comment by benplum** [comment]
Videos are not displayed at all on mobile. You can't auto play a video due to bandwidth concerns, so loading the video would be pointless. Adding a "state" method is a great idea.

**Comment by benplum** [comment]
You can check if a video is playing by accessing the internal plugin data:

```
var data = $(".background").data("fsBackground");
if (data.playing) {
    ...
}
```
