### ISSUE TITLE
CDN cache buster string makes Lightbox think image is webpage

### ISSUE THREAD

**Issue by matthisamoto** [Formstone/Formstone#241]
Using Lightbox with Shopify CDN assets, they always include a cache busting URL var like `&v=XXXXXX` and this is causing Lightbox to think it should use an iframe to load a page.

I tested the `source.match` out directly with the URL string and I'm guessing that Formstone checks the end of the string for a filename. Thinking stripping the URL vars off before detecting could fix this, but not sure if there are other factors to consider there?

I see that I can add `data-lightbox-type="image"` to the object to force it to type as an image, but I just figured this could be a common-ish problem for CDN hosted images. Curiously using `type: "image"` in the JS function options for lightbox didn't accomplish this same fix.

**Comment by benplum** [comment]
I'll look into the file type matching, there's probably a better way to handle it. Setting `type: "image"`in the initialization options won't work since it's an individual instance option, hence the individual `data-lightbox-type` option (we can't assume all lightbox links will match that type).

**Comment by benplum** [comment]
Fixed in 1.4.3! Had to adjust the regex for image detection.
