### ISSUE TITLE
Grid: Nested 'contained' columns misaligned.

### ISSUE THREAD

**Issue by fowlercraig** [Formstone/Formstone#242]
Hey there, I'm having trouble aligning 'contained' columns. In a previous version fo Formstone, the following code would work great and everything would be aligned perfectly. 

```
<div class="fs-row">
  <div class="fs-cell fs-all-full">
    <div class="fs-cell fs-all-third fs-contained">1</div>
    <div class="fs-cell fs-all-third fs-contained">2</div>
    <div class="fs-cell fs-all-third fs-contained">3</div>
  </div>
</div>
```

But now this breaks the layout. Instead of laying out side by side, the columns are stacked on top of each other. If I try the following code, the alignment breaks the grid. 

```
<div class="fs-row">
  <div class="fs-cell fs-all-full">
    <div class="fs-row">
      <div class="fs-cell fs-all-third fs-contained">1</div>
      <div class="fs-cell fs-all-third fs-contained">2</div>
      <div class="fs-cell fs-all-third fs-contained">3</div>
    </div>
  </div>
</div>
```

I'm aiming for it to look like this screenshot, but without breaking the grid as it does currently:
https://www.dropbox.com/s/euujvd6a3vof1m1/Screenshot%202017-12-13%2015.30.02.png?dl=0

**Comment by benplum** [comment]
Interesting - we'll look into nested contained cells.

**Comment by benplum** [comment]
After looking at the screenshot again, this is actually the expected behaviour. The `contained` modifier removes the left and right cell gutters, so the cells fill the entire with of the row. You will need to add some custom styling to a container to force a matching width.
