### ISSUE TITLE
Number field does not allow non-required behavior

### ISSUE THREAD

**Issue by alexsorokoletov** [Formstone/Formstone#244]
Hi!

At this time there is no way to use Formstone with number inputs when number input is not a required field. Formstone's code always sets it to 0 (https://github.com/Formstone/Formstone/blob/master/src/js/number.js#L244)

HTML5 number field can be empty.

Please advise about any workaround. Thank you.

**Comment by benplum** [comment]
This is fixed in 1.4.4.
