### ISSUE TITLE
Background Video on Mobile

### ISSUE THREAD

**Issue by nhall** [Formstone/Formstone#247]
This is more of a question than an issue. Some mobile browsers now allow videos to autoplay if the audio channel has been stripped. This can be a great experience if there is a sensible download size. I know that the background plugin is designed to night even attempt to load videos on mobile. I see in the source there are two places I see where we are checking for mobile:

https://github.com/Formstone/Formstone/blob/master/src/js/background.js#L334
https://github.com/Formstone/Formstone/blob/master/src/js/background.js#L410

If I remove these I can see video autoplay on devices like the iPad. However, it still does not autoplay on the iPhone. Is there another check that an iPhone would fail? I've walked through the code and I am not sure what else is missing. I can see that the video element is created but it does not play.

Thanks!!

**Comment by benplum** [comment]
It may have to do with how much of the video is covered by other content. Apple relaxed autoplay restrictions a while back, but it still seems pretty inconsistent in my experience: 

https://webkit.org/blog/6784/new-video-policies-for-ios/

I'm thinking in your case some of the video is unobstructed on the iPad, but fully covered by a DOM element on iPhone? If that's the case we could add an option to force the video on mobile, but it would still be up to the developer to ensure the overlaid content doesn't fully cover the background. 

EDIT: There's also a new `playsinline` attribute for the `<video>` tag. Let me know if adding that to the generated markup fixes the issue and we can push a new release.

**Comment by nhall** [comment]
Thanks so much for taking a look.  I tried to add the `playsinline` attribute with no success. And I was wrong about my first assumption, it did not in fact play on the iPad.

I"m going to look into it further. The strange thing is that I can get it to play automatically on mobile when I add a player in markup. It has the same source as what is generated, strange. Maybe it's because I'm adding it with JS?

Anyways, thank you for the guidance, I'll let you know what I figure out.

Thanks!

**Comment by benplum** [comment]
Just wanted to follow up here. After adding the `playsinline` attribute I'm seeing the video auto play in the iOS simulator, even with an element overlapping the video. When you have a chance, let me know if you are seeing the demo video auto play on your iOS devices: http://dev.formstone.it/components/background.html

**Comment by nhall** [comment]
I can confirm that I can indeed see the "Video" demo play on that page. Thanks!

**Comment by benplum** [comment]
This is up on v 1.4.8.
