### ISSUE TITLE
The windows scrolls to the top when the menu opens

### ISSUE THREAD

**Issue by hadilnc01** [Formstone/Formstone#249]
Hello,

I'm using your navigation shifter library and I love it! However, I just made the mobile menu fixed and I noticed that whenever the mobile menu opens, the window scrolls to the top. Is there a way to prevent this?

Below is the code:
**For the toggler:**
`<a href="javascript:;" id="mobile-nav-toggle" class="shift-nav-handle"><i class="fa fa-bars" aria-hidden="true"></i></a>`

**JS:**
```
var toggler = function() {
        var navigation_toggle = $("#mobile-nav-toggle");
        var mobile_menu = $("#mobile-menu");

        mobile_menu.navigation({
            type: "push",
            gravity: "left",
            maxWidth: "767px",
            label: false
        });

        mobile_menu.on("open.navigation", function() {
            navigation_toggle.find("i").removeClass("fa-bars");
            navigation_toggle.find("i").addClass("fa-times");
        }).on("close.navigation", function() {
            navigation_toggle.find("i").addClass("fa-bars");
            navigation_toggle.find("i").removeClass("fa-times");
        });
    };
```

**Comment by benplum** [comment]
This is due to how an `<a>` tag works. The script you have in the `href` attribute isn't preventing the default event, so the browser is jumping to the top. Try swapping it out for a `<button type="button">` tag (this is also a more accessible solution when paired with proper `aria` attributes).  

```
<button type="button" id="mobile-nav-toggle" class="shift-nav-handle"><i class="fa fa-bars" aria-hidden="true"></i></button>
```

**Comment by hadilnc01** [comment]
Hi Ben,

Thank you for your reply but the problem is still there. I remove the <a> and used the button HTML you shared but the window is still scrolling up.

**Comment by benplum** [comment]
Can you share a live example of the behavior?
