### ISSUE TITLE
Compatibility issue with bootstrap

### ISSUE THREAD

**Issue by semismurf** [Formstone/Formstone#25]
I know that your library is designed to be a replacement for bootstrap.  I would like to bring up that in my implementation that leverages some of bootstraps functionality alongside some of your widgets there is a compatibility issue with the "carousel()" methods due to naming conflicts.

The fix to it is to comment out the whole carousel code block from bootstrap. (\* Bootstrap: carousel.js v3.3.4)

It would be nice to maybe use a different name for your methods so they will play more nicely together.  

:dancer: :dancer:

**Comment by benplum** [comment]
I believe Bootstrap can be compiled without the carousel files. 

That said I do understand the concern and will look into a possible fix (maybe a .noConflict like with jQuery?), but feel the benefits of using a common naming structure outweighs minor overlaps in API between two unrelated libraries.

**Comment by semismurf** [comment]
I agree that you should not break your naming structure. This is just a suggestion and not a "bug" per say.

Note that you seem to prefix your css attributes and other elements with fs in your naming conventions.  It would make your framework a bit more compatible in general if you were to also prefix your methods with fs.

Example:
$(".target").fscarousel("");

I know this would be annoying to do though >_<

:octopus: :octopus:

**Comment by benplum** [comment]
There is now a "namespaced" handler for each plugin: 

```
.carousel  ->  .fsCarousel
.lightbox  ->  .fsLightbox
```

This needs to be implemented throughout all plugins internally, but should help your immediate issue.
