### ISSUE TITLE
Prevent select dropdown from changing

### ISSUE THREAD

**Issue by ehudg** [Formstone/Formstone#250]
Hi

Is it possible to prevent or reverse the change event in the dropdown?

When the user select an option in the dropdown, I want the ability to raise a confirm box, and if the user click 'No'  revert back to original option. I have the confirmation box, can you kindly direct me to how I can revert back to the previous option?

Thank you.

**Comment by benplum** [comment]
There currently isn't a way to cancel the value change, and this follows the browser behavior: 

https://jsbin.com/wekabekifo/edit?html,css,js,output

You could try caching the current value before the change event, then updating it after based on the user response.
