### ISSUE TITLE
Vertical Drifting, Sensitive Carousel Swiping

### ISSUE THREAD

**Issue by mimoduo** [Formstone/Formstone#251]
Gotta start by saying formstone carousels rock!!

Though, on mobile, swiping between carousel can often be extremely finicky.
Once you swipe to once slide, and scroll a bit diagonally, the carousel often swipes to another slide.

I know this is extremely complex but a bit of a forgiveness threshold for swiping might do wonders!

Sincerely,
Bryan Stoner

**Comment by benplum** [comment]
Thanks! It's a tough problem, but I'm absolutely open to other implementation ideas. Carousel uses Touch internally:

https://github.com/Formstone/Formstone/blob/master/src/js/touch.js#L208

**Comment by nhall** [comment]
This seems to work pretty good to help with the drifting. 

```
$(document).bind("touchstart", onTouchStart)
	.bind("touchmove", onTouchMove);

function onTouchStart(e) {
	touchStartX = e.originalEvent.touches[0].clientX;
	touchStartY = e.originalEvent.touches[0].clientY;
}

function onTouchMove(e) {
	if ($(e.target).closest(".js-carousel").length == 1) {
		var touchEndX = e.originalEvent.changedTouches[0].clientX;
		var touchEndY = e.originalEvent.changedTouches[0].clientY;
		if (Math.abs(touchStartX - touchEndX) > Math.abs(touchStartY - touchEndY)) {
			e.preventDefault();
		}
	}
}
```

Check to see if you've swiped more horizontally than vertically. If you do, take away the page scroll. That way you don't have to keep centering the content if you don't give a level swipe.

**Comment by benplum** [comment]
This does seem to [be helping](https://github.com/Formstone/Formstone/blob/7446234e9ca9cad30dd5a1197fdc95bbd9221015/src/js/carousel.js#L1340-L1342) with the rogue swipes. I have this up on the dev branch. Let me know if it resolves the issue and we'll get it released.

**Comment by nhall** [comment]
I think this helps keep the carousel in focus. Nice update. Thanks!

**Comment by benplum** [comment]
This is up on v 1.4.8.
