### ISSUE TITLE
Custom Controls won't hide based on 'show' setting?

### ISSUE THREAD

**Issue by matthisamoto** [Formstone/Formstone#254]
I may be doing something wrong, but I'm using the custom controls and while Carousel will tell the control buttons whether they are `fs-carousel-visible` or not, it doesn't seem like it will tell my custom `.controls` whether to display or not based on the amount of items to show. 

I'm showing 4 thumbnails at a time, and when there's 1-4 thumbs, it shouldn't display controls at that breakpoint, like it would behave through the typical controls setup.

**Comment by benplum** [comment]
Can you set up a quick demo? I'm seeing the `fs-carousel-visible` class being applied to the container and both controls on the [custom controls demo](https://formstone.it/components/carousel/demo/).
