### ISSUE TITLE
Dropdown:  Use html() instead of text() to build option labels

### ISSUE THREAD

**Issue by Bonscho** [Formstone/Formstone#255]
It would be nice to respect HTML content of select options while building the custom dom. I think most of the dom elements that are valid option child nodes are valid button child nodes.

**Comment by Bonscho** [comment]
Roll back! 
I just saw that we can define the label using the label data attribute of the options to accomplish custom option content. 
I think the issue could get closed.

**Comment by benplum** [comment]
Yup - this was added because nesting html in an `option` tag is not technically valid (although it may work in some browsers).
