### ISSUE TITLE
Checkbox stopPropagation issue with WooCommerce Payment Methods

### ISSUE THREAD

**Issue by matthisamoto** [Formstone/Formstone#257]
Something about the way WooCommerce payment methods are laid out in markup inside labels is causing an issue with their events when I am using Checkbox to restyle the radio buttons.

I found that commenting out line [179 in src/js/checkbox.js](https://github.com/Formstone/Formstone/blob/master/src/js/checkbox.js#L179) where it stops event propagation fixes this issue and allows the rest of the events tied to choosing a payment method to fire.

I'm not sure what other things this is stopping that are necessary, so I'm curious if it's something that can even be amended?

```
    /**
     * @method private
     * @name onClick
     * @description Handles click
     */

    function onClick(e) {
     // e.stopPropagation();

      var data = e.data;

      if (!$(e.target).is(data.$el)) {
        e.preventDefault();

        data.$el.trigger("click");
      }
    }
```

**Comment by benplum** [comment]
Fixed in 1.4.11.
