### ISSUE TITLE
Client Side Image Resizing 

### ISSUE THREAD

**Issue by warrenkc** [Formstone/Formstone#259]
For the file uploader, is it possible to resize images before uploading? Also does it support parallel uploads for speed?

**Comment by benplum** [comment]
Resizing would probably need to be handled server side, although you might be able to use the `beforeSend` callback to modify the form data before it's sent. You can control the number of parallel uploads with the `maxConcurrent` option (defaults to 2), although this can be limited by the max connections your browser or server will allow.

**Comment by warrenkc** [comment]
Thank you. Your quick detailed response is amazing.
