### ISSUE TITLE
What about adding "composer.json" .. or at least provide a full dist download

### ISSUE THREAD

**Issue by DerDu** [Formstone/Formstone#26]
..would be helpful ;)

.. or am i just stupid .. because i cant get it to work :(

**Comment by benplum** [comment]
I've never used composer but am interested in hearing more about the process and how it will benefit the project.

**Comment by Xymanek** [comment]
Formstone is **HTML/CSS/JS** library. Composer is for adding **PHP** libraries to your site. Pretty sure it's not suitable here

**Comment by benplum** [comment]
@Xymanek That was my assumption, just wanted to make sure I wasn't missing anything.
