### ISSUE TITLE
Checkbox: Event trigger on deselection leads to weird scroll behavior

### ISSUE THREAD

**Issue by Bonscho** [Formstone/Formstone#260]
If presenting a long list of radio buttons so scrolling is required, the overflow container – mostly the document – will scroll to nowhere, after selecting a radio button. I think this is caused by the focus related event triggering on (automatic) deselection of the previously selected radio button. 

If utilizing checkboxes instead of radio buttons this weird behavior do not happen.

**Comment by benplum** [comment]
Fixed in 1.4.11.
