### ISSUE TITLE
Advancement or question re: uploader

### ISSUE THREAD

**Issue by jackttcoms** [Formstone/Formstone#266]
Hi there,

I have one quick question/advancement for the upload. Is it possible to have more than one drop zone within one form so it would like FORM|fileinput1, fileinput2|FORM

Thanks in advance

**Comment by benplum** [comment]
Absolutely, each instance can be configured individually with inline options: 

```
<form>
  <div class="upload_1" data-upload-options='{"action":"//example.com/handle-upload-1.php"}'></div>
  <div class="upload_2" data-upload-options='{"action":"//example.com/handle-upload-1.php"}'></div>
</form>
```
