### ISSUE TITLE
Edge/IE swap method bug

### ISSUE THREAD

**Issue by timalbert** [Formstone/Formstone#267]
As best I can tell, the swap event 'deactivate.swap' fires when clicking anywhere on the screen in Edge/IE. I am not sure if this is related to issue #14?

We leverage these to animate the element being swapped.

**Comment by chrisg88** [comment]
We've recently experienced something similar, but not quite the same. 

Swap appears to activate / deactivate, however the activate.swap / deactivate.swap events never seem to fire - occurred only on Edge. 

Agree that this sounds possibly related to the issue linked above.
