### ISSUE TITLE
Disable carousel controls

### ISSUE THREAD

**Issue by nhall** [Formstone/Formstone#268]
What do you think about adding a "disabled" attribute to the carousel control buttons. Then we can remove it when `.fs-carousel-visible` is applied. The reason I would like to add a disabled attribute is because once the button has been disabled it will no longer be a tab stop. The button doesn't do anything so I think it makes the most sense to be disabled.

I'm not sure if we should add this attribute to the custom controls since we don't know what element the controls will be. They could be an element that shouldn't receive the disabled attribute. On the flip sided I could also see using custom controls just because I want button element controls positioned separate from the carousel.

What are your thoughts?

**Comment by benplum** [comment]
Controls will now be marked disabled when appropriate. Let me know if there are any other accessibility concerns you've found.
