### ISSUE TITLE
prevent auto upload images, if one of them cancelled

### ISSUE THREAD

**Issue by harishksoft** [Formstone/Formstone#271]
@benplum  I have a set of images in the queue and the auto upload is false, have an upload button on the bottom to initiate the upload. When one of the images is cancelled, the rest of the images will upload automatically if the auto upload attribute is even false.

This is the jsfiddle demo: https://jsfiddle.net/7zmkgfyj/4
PHP server side code is not included in example, so instead of uploading it will show an error, but clearly you will get an idea about what's happening when one of the uploaded document cancelled.

**Comment by harishksoft** [comment]
@benplum is there any option to solve this?

**Comment by benplum** [comment]
This is expected behavior for the plugin. Setting `autoUpload` to `false` means that the entire upload process will wait for a call to the `start` method, instead of starting when the files are dropped. Once the upload has been started, the plugin will continue to run through the queueing and uploading process until all dropped files are complete. 

If you need to cancel all uploads when a single upload is canceled, don't pass an index to the `abort` method:

```
$('.upload').upload('abort');
```

**Comment by harishksoft** [comment]
> This is expected behavior for the plugin. Setting `autoUpload` to `false` means that the entire upload process will wait for a call to the `start` method, instead of starting when the files are dropped. Once the upload has been started, the plugin will continue to run through the queueing and uploading process until all dropped files are complete.
> 
> If you need to cancel all uploads when a single upload is canceled, don't pass an index to the `abort` method:
> 
> ```
> $('.upload').upload('abort');
> ```

@benplum i don't want to cancel all, just want to cancel one or two of them. I think you don't get my point. If i upload 2 files by mistake in a set of 10 files, how do i cancel that two? as per current plugin behavior, we can cancel only one file, rest will upload auto.

**Comment by benplum** [comment]
You should set up something like in the demo, where each item has a cancel button. This way the user can cancel whatever files they want. If you need to do it programmatically, just figure out the indicies to cancel and call the `abort` method for those: 

```
var cancelThese = [2, 4, 5];
for (var i = 0; i < cancelThese.length; i++) {
   $('.upload').upload('abort', cancelThese[i]);
}
```

**Comment by harishksoft** [comment]
> You should set up something like in the demo, where each item has a cancel button. This way the user can cancel whatever files they want. If you need to do it programmatically, just figure out the indicies to cancel and call the `abort` method for those:
> 
> ```
> var cancelThese = [2, 4, 5];
> for (var i = 0; i < cancelThese.length; i++) {
>    $('.upload').upload('abort', cancelThese[i]);
> }
> ```

@benplum i have just setup the demo downloaded from git. 
![image](https://user-images.githubusercontent.com/27539252/60598124-c7590c80-9dc9-11e9-96c9-26e0d88c5a9b.png)
i hope you have run through the jsfiddle demo, after uploading it shows cancel button for each files. But if i uploaded 5 files and want to cancel two of them, is not possible. after cancel of the first one the upload auto start and can't cancel the second one. this is the fiddle https://jsfiddle.net/7zmkgfyj/4

**Comment by benplum** [comment]
Are you saying you can't cancel the second one because the upload happens too fast? Or do you think the user will need remove a file before actually starting the upload process?

**Comment by harishksoft** [comment]
Yes. I want to remove files before actual upload starts. So that user can
remove files if they upload by mistake.

**Comment by benplum** [comment]
That makes more sense. 

You'll want to grab 1.4.14. There's a new demo for 'Manual Uploads' you can try: https://formstone.it/components/upload/demo/

**Comment by harishksoft** [comment]
Great... let me check it out. Thanks for building such an awesome plugin :)

**Comment by harishksoft** [comment]
So updating the core.js and upload.js to latest version will solve  the
problem. Right?
