### ISSUE TITLE
Disable y-axis scrolling while swiping through Carousel on mobile

### ISSUE THREAD

**Issue by fowlercraig** [Formstone/Formstone#272]
While advancing through a carousel on mobile, I notice that horizontal swiping needs to be very precise or the the carousel will scroll vertically, sometimes out of the viewport.

**Comment by benplum** [comment]
Can your provide more detail on your issue? Is there a specific site or device/browser this is happening on? I'm not sure I fully understand the problem.

**Comment by fowlercraig** [comment]
If you view your carousel demo on a mobile phone and make a slightly diagonal left swipe to advance the carousel, you'll notice that the screen scrolls up or down a bit. 

While viewing https://dimsemenov.com/plugins/royal-slider/ on a mobile, the same motion won't scroll the screen at all. It takes a more aggressive diagonal swipe in order for it to scroll up/down.

**Comment by benplum** [comment]
I think it comes down to how you use your device. The plugin considers many factors to determine when to cancel the user's scroll including distance moved and time between touches. We spent time testing and tweaking and feel the current version strikes a good balance. If you like how other work I would encourage you to use those.
