### ISSUE TITLE
Dropdowns are disable on mobile

### ISSUE THREAD

**Issue by felicianuniversity** [Formstone/Formstone#274]
Hi,  My website is not expanding the dropdowns when you view them on mobile devices.  Any mobile device.

**Comment by benplum** [comment]
It looks like the site is still using 1.1.3. You can check by running `Formstone.Version` in the console. Try updating to the latest version.

**Comment by felicianuniversity** [comment]
Thanks!!!  I am unfamiliar with this process. I am hosting the site with Pagely.  Is this something I can do or maybe replace the folder and all the files of Formstone?
________________________________

**Comment by felicianuniversity** [comment]
Ok,  Is this where I would do the update with my host?  Not to sure.  Thanks
https://support.pagely.com/hc/en-us/articles/202660984-Using-WP-CLI-Command-Line-Tools

**Comment by felicianuniversity** [comment]
I was able to get some help from my host, but they said it doesn't exist as a plugin?

I have it as a folder on the server, dont remember it being a plugin.

(ommitted):~/sites/dev.felician.edu$ wp plugin get formstone
Error: The 'formstone' plugin could not be found.
--
(ommitted):~/sites/dev.felician.edu$ grep -iR 'formstone' wp-content/plugins | wc -l

Thanks!

**Comment by benplum** [comment]
It's not a WordPress plugin. The page is loading a compiled javascript file that needs to be updated. I think you need to contact whoever built the site.

**Comment by felicianuniversity** [comment]
Understood.  is there any other way to do this except the way you said above?  The developer before is no longer available. Just trying to find a way to ge the dropdowns to work with your scripts.

You said try this:
You can check by running Formstone.Version

**Comment by benplum** [comment]
Running `Formstone.Version` will simply tell you want version is being loaded. 

I can't really say if there is another way or not since I don't know anything about how this site/theme is built. Ultimately you will need someone with front end development and WordPress experience to help in a hands on way.

**Comment by felicianuniversity** [comment]
Thanks
