### ISSUE TITLE
Картинка не открывается в полный размер

### ISSUE THREAD

**Issue by maaxim-one** [Formstone/Formstone#276]
Картинка **800x800**, а открывается **180x779**.
Скриншот: https://yadi.sk/i/aM8AtPDnF6h-_A

**Comment by benplum** [comment]
You may have some CSS that is preventing the plugin from adjusting the image to the proper size. Can you send a working/live example?

**Comment by maaxim-one** [comment]
Я использовал прямо из "коробки".
Вот JS код:
`$('.lightbox').lightbox();`
А CSS я не трогал, только импорт(webpack):
`@import "~formstone/dist/css/lightbox.css";
@import "~formstone/dist/css/themes/light/lightbox.css";`
