### ISSUE TITLE
XSS Vulnerability

### ISSUE THREAD

**Issue by adrianomarcmont** [Formstone/Formstone#286]
Hi Formstone team.

We are BRZTEC, a offensive information security firm from Brazil. 

When performed a pentest in one of our customers we found a XSS vulnerability that affect default installation of Formstone. 

Please, do you can tell us a secure channel to send to yours more details about this vulnerability?

Please visit the website https://cveform.mitre.org/ and see more details on how to request a CVE ID and please acknowledge the finding to our company. 

If you have any difficulties let us help you.

Best Regards.

Adriano Monteiro
Information Security Specialist
adriano@brztec.com
+55 31 99255-3329
https://www.brztec.com

**Comment by benplum** [comment]
You can email me: mr@benplum.com

**Comment by adrianomarcmont** [comment]
Done!

**Comment by benplum** [comment]
Thanks, resolved in 1.4.17.

**Comment by adrianomarcmont** [comment]
Thank you!
