### ISSUE TITLE
Dropdown preventing change event firing on select from external code

### ISSUE THREAD

**Issue by matthisamoto** [Formstone/Formstone#288]
I'm having a problem with Dropdown and some code initiated on the `change` event for `select` element from a Craft CMS-based forms plugin.

Basically, the select changes, but the event on the select element itself doesn't seem to run. I tried to use `dispatchEvent` on it but ran into a call stack problem as it triggered itself over and over. It did however get the event listener function in the plugin to trigger before the train ran away.

Is there something preventing externally attached listeners from firing on the element itself?

**Comment by benplum** [comment]
I don't believe so, it's just listening for a change and [updating the internal data to match](https://github.com/Formstone/Formstone/blob/ed2bea411514991c8bb75a671313f6ac56590159/src/js/dropdown.js#L549).

What is Craft doing on the front end side, or is it possible to share a demo/example?
