### ISSUE TITLE
Lightbox gallery using In-Line Content won't load next element

### ISSUE THREAD

**Issue by matthisamoto** [Formstone/Formstone#296]
See [Demos page](https://formstone.it/components/lightbox/demo/), "In-Line Content".

Open the first item, try to hit the next control button, it loads the page inside the lightbox instead of the next in-line content element.

**Comment by benplum** [comment]
<img src="https://media3.giphy.com/media/X83Y7r03T6uty/200.gif">

**Comment by benplum** [comment]
Fixed in 1.4.20.
