### ISSUE TITLE
Distorted Images in Lightbox

### ISSUE THREAD

**Issue by ianjwhitmore** [Formstone/Formstone#299]
I am running into an ongoing issue with images distorting and displaying extremely narrow in the Lightbox plugin. 

I'd like to provide a development link privately if possible. 

This is happening in Chrome and Safari.

Attaching a screenshot here for reference. 
<img width="326" alt="Screen Shot 2021-03-15 at 9 23 55 AM" src="https://user-images.githubusercontent.com/24276603/111186453-44152580-8570-11eb-86fb-4d2ae7d68b4a.png">

**Comment by benplum** [comment]
This typically happens when global site styles are setting a width/height on the image. Try unsetting with/height on lightbox images.

**Comment by ianjwhitmore** [comment]
Thanks! That was the answer!
