### ISSUE TITLE
.navigation("open") not working as expected

### ISSUE THREAD

**Issue by simplethemes** [Formstone/Formstone#3]
I'm attempting to open the menu via another link on the page (in addition to the #handle method in docs).

Am I missing something or is this a bug?

```
$( "a.btn" ).on( "click", function() {
  $("#nav").navigation("open");
});
```

**Comment by benplum** [comment]
Strange, I can't actually replicate this. If you run the following from the console on the documentation site, the nav will open/close as expected:

`$(".js-navigation").navigation("open");`

then:

`$(".js-navigation").navigation("close");`
