### ISSUE TITLE
Dropdown accessibility

### ISSUE THREAD

**Issue by doniaBlair** [Formstone/Formstone#300]
I have a dropdown element with the external option set to true. I see the .fs-dropdown div has tabindex="0", but when that has focus and you hit Enter, the first link is automatically launched instead of opening the dropdown options to select an option. I checked the demos page and the External Links demo does the same. Is there a workaround or can this be fixed?
```
$('.extra-callouts .buttons select').each(function() {
    $(this).dropdown({
        theme: '',
        external: true
    });
});
```

**Comment by benplum** [comment]
This is expected behavior for the plugin. Hitting enter inside a form will submit the form, or in this case trigger the link. You could always write a custom link handler based on the [standard functionality](https://github.com/Formstone/Formstone/blob/master/src/js/dropdown.js#L834).

**Comment by doniaBlair** [comment]
Ok I'll look into that. So just to clarify, there's currently no way for someone using the keyboard to navigate the page to open the dropdown options?

**Comment by benplum** [comment]
Once focused, you can use the keyboard arrows to cycle through the options, just like a standard select field.

**Comment by doniaBlair** [comment]
Ok thanks @benplum! Appreciate the help
