### ISSUE TITLE
Dropdown and fixed elements

### ISSUE THREAD

**Issue by pensiero** [Formstone/Formstone#31]
If there is a fixed element, for example something with:

```
position: fixed;
bottom: 0;
left: 0;
width: 100%;
height: 300px;
background-color: #FFF;
```

and there is a dropdown right near the upper border of the fixed bottom, if the height of the dropdown is `< 300px` then it will open under the fixed element.

This is obvious, because there is enough height between the dropdown and the bottom of the window.
However, it would be nice to say "hey dropdown, open toward top (instead of bottom) if there are `< X` under you (where X could be `300px`).

What you think?

**Comment by benplum** [comment]
Right now there is a check to see if the element is near the edge of the body. Unfortunately, a fixed positioned element might never hit that bottom edge. I would be interested in a different solution, but am unsure exactly where to start.

**Comment by pensiero** [comment]
A possible solution could be an `int` stored in a custom variable that is summed to the bottom edge. For example, if the bottom edge is `600px`, and the variable is `100px`, the script will check if the dropdown hit `500px` instead of `600px`.

Could you please tell me what are the lines of code that check when the dropdown hit the bottom edge?

**Comment by benplum** [comment]
That's sort of what's happening here: https://github.com/Formstone/Formstone/blob/master/src/js/dropdown.js#L348-L356

**Comment by pensiero** [comment]
So it could be something like

```
if (offset.top + optionsHeight > bodyHeight - optionsOffsetFromBottom) {
```

instead of [this line](https://github.com/Formstone/Formstone/blob/master/src/js/dropdown.js#L354).

Where `optionOffsetFromBottom` is a custom option (i'm not so good with var names :P).

**Comment by benplum** [comment]
There is a new option, `bottomEdge`, that allows you to set a custom threshold.

**Comment by pensiero** [comment]
Fantastic! I will try it tomorrow and let you know

**Comment by pensiero** [comment]
It works! thanks
