### ISSUE TITLE
Mention in documentation how Dropdown decides when to use top or bottom based on the height of BODY

### ISSUE THREAD

**Issue by thinsoldier** [Formstone/Formstone#32]
Some extra fancy modern layouts may have body set to 100% of html which is 100% of the viewport. In that scenario if the dropdown options list is kind of long it will always be shown above the element instead of below.

**Comment by cbier** [comment]
This feature is great but causes a problem in my particular instance where the content of my website is wrapped in an absolutely positioned element. The body tag has a nearly 0 height so the dropdown is below the and always shows the dropdown above the select.

I am going to try and add an option to the dropdown script to turn this off. Unless it already exists? I don't see it in the docs. Thanks!

**Comment by cbier** [comment]
I added a boolean option and named it `autoFlip`. Then I added it to this if statement in dropdown.js in the `openOptions` function (starting on line 355):

```
            // Calculate bottom of document
            if ((offset.top + optionsHeight > bodyHeight - data.bottomEdge) && data.autoFlip) {
                data.$dropdown.addClass(RawClasses.bottom);
            }
```

I set it the option to true by default so it doesn't break existing installations (starting on line 768):

```
            defaults: {
                bottomEdge     : 0,
                cover          : false,
                customClass    : "",
                label          : "",
                external       : false,
                links          : false,
                mobile         : false,
                trim           : 0,
                autoFlip       : true
            },
```

Then, in the init, I simply include the option:

```
    $("select").dropdown({
        autoFlip: false
    });
```

I didn't really work hard to understand the code so I could have left out a step, but this works. The code is very easy to understand by the way. Thanks for such a great tool!

I would fork this repository and submit a pull request but I don't have time at the moment.
