### ISSUE TITLE
Trigger Lightbox on Checkbox

### ISSUE THREAD

**Issue by simplethemes** [Formstone/Formstone#33]
Hi, I'm trying to show/hide a Lightbox based on a Checkbox (checked) value.

https://jsfiddle.net/ryy545yL/

Additionally, the Lightbox options don't seem to be working as expected. Could you let me know if what I'm trying to do is possible or if I'm just doing it wrong?

Thanks!

**Comment by benplum** [comment]
Seems like the checkbox is opening the lightbox in your example. Do you also want to uncheck the box when closing the lightbox? 

I did fix the issue with options not working.

**Comment by simplethemes** [comment]
I'm using v0.6.14 in the fiddle above.
https://jsfiddle.net/ryy545yL/

The problem I'm experiencing is the options (minwidth, maxwidth, top ) are ignored and the lightbox content does not show again once closed.

`$("#monogramming").change(function() {
    if(this.checked) {
        $.lightbox(
            $('#inline_content'),
            {
                "minWidth":600,
                "minHeight":800,
                "top":0
            } );
    }
});`
