### ISSUE TITLE
Dropdown - Work around overflow:hidden parent elements.

### ISSUE THREAD

**Issue by thinsoldier** [Formstone/Formstone#36]
Sometimes Dropdown has to be used with a parent element that has a fixed height and overflow hidden. 

This causes long option lists to be cut off.

It would be nice if there was an option to have Dropdown's option list moved higher in the dom tree and then absolutely positioned to line up with the Dropdown box.

I specifically say "higher in the dom tree" and not "the very top" because I remember old IE and other dropdown scripts had problems where select elements would render above the dark page overlay of lightbox scripts.

![screen shot 2015-06-23 at 4 22 15 pm](https://cloud.githubusercontent.com/assets/373834/8316308/129e635e-19c4-11e5-87af-35db9ccefcbd.png)

**Comment by thinsoldier** [comment]
possibly useful in relation to this enhancement:
http://github.hubspot.com/tether/
http://github.hubspot.com/select/docs/welcome/

**Comment by benplum** [comment]
These are great examples, thanks for sharing. My biggest concern is scrolling within fixed positioned containers. One solution could be to close the options pane when scrolling outside of the Dropdown? I'll give it some more thought, and welcome contributions to the solution.

**Comment by benplum** [comment]
Closing as there aren't any current plans to add this.
