### ISSUE TITLE
Lightbox - Autoplay Vimeo videos

### ISSUE THREAD

**Issue by allaire** [Formstone/Formstone#37]
Looks like when you pass query strings (//player.vimeo.com/video/XXXX?title=0&byline=0&portrait=0&autoplay=1&badge=0) they are not passed to the iframe building.

**Comment by ryandoss** [comment]
I just noticed and second this, would be nice for it to not strip url query params. Or provide an option to not strip them.

Added my own fix for now.
https://github.com/ryandoss/Formstone

I added an option called "formatVideo" that defaults to "true". Change to false and the source will be pulled directly from the anchor href and ignore video formatting. It's a quick fix.. better to always format the videos as he's done and append the query params at the end.
