### ISSUE TITLE
Scrollbar for dropdown

### ISSUE THREAD

**Issue by gewaking** [Formstone/Formstone#4]
For some reason scrollbar does not work for dropdown anymore, in previous version it was working fine.

**Comment by benplum** [comment]
This was removed during the transition to the single library, it will return in an update soon.

**Comment by k-lusine** [comment]
Hi, is this feature now available, I can't use formstone scrollbar to style the scrollbar of a select that has been styled using formstone dropdown

**Comment by benplum** [comment]
This is now available.
