### ISSUE TITLE
Lightbox - Why isn't there maxWidth parameter?

### ISSUE THREAD

**Issue by aigarinsh** [Formstone/Formstone#45]
I am unable to set maxWidth parameter, cause there isn't such, though there is minWidth. The only way is to to use CSS and set it globally. Otherwise if I specify data-lightbox-width it doesn't resize on smaller screens, but not specifying the width it stretches too much on larger screens.

**Comment by benplum** [comment]
A maxWidth would be helpful. Are you displaying iframed or inline content?

**Comment by aigarinsh** [comment]
iframed

**Comment by andrewhinde** [comment]
I've been looking to set a percentage for width/height with a maximum pixel value and I think this could work for your solution as well.

I've added maxWidth and maxHeight to the defaults object (around line 1330 of lightbox.js), then modified the sizeContent() function just above where it sets Instance.targetHeight and Instance.targetWidth

``` javascript
var heightPct = 0.60;
var widthPct = 0.75;

// Figure out and set height
var height = Instance.windowHeight * heightPct;
if(height > Defaults.maxHeight){ height = Defaults.maxHeight; }
Instance.targetHeight = Instance.$el.data(Namespace + "-height") || height;

// Figure out and set width
var width = Instance.windowWidth * widthPct;
if(width > Defaults.maxWidth){ width = Defaults.maxWidth; }
Instance.targetWidth  = Instance.$el.data(Namespace + "-width") || width;

//Instance.targetHeight   = Instance.targetHeight || (Instance.$el ? Instance.$el.data(Namespace + "-height") : null);
//Instance.targetWidth    = Instance.targetWidth  || (Instance.$el ? Instance.$el.data(Namespace + "-width")  : null);
Instance.maxHeight        = (Instance.windowHeight < 0) ? Instance.minHeight : Instance.windowHeight;
Instance.isIframe         = $object.is("iframe");
Instance.objectMarginTop  = 0;
Instance.objectMarginLeft = 0;
```

If you set your heightPct and widthPct to 1, it shoulf work for you, just set maxWidth and maxHeight on your defaults, or pass them in when initializing lightbox.

I've also attached the full modified file (just change the file extension to .js)
[lightbox.txt](https://github.com/Formstone/Formstone/files/83158/lightbox.txt)

**Comment by benplum** [comment]
maxWidth and maxHeight parameters for element modals will be landing in 1.1.0. Checkout the lightbox branch for a preview.

**Comment by benplum** [comment]
Added in 1.1.0.
