### ISSUE TITLE
Html inside dropdown options

### ISSUE THREAD

**Issue by pensiero** [Formstone/Formstone#47]
Is it possible to show some custom html tags inside the dropdown options?
I have an option like this: 

```
<option value="hello"><span class="icon icon-hand"></span> Hello</option>
```

Obviously usually this has no sense in an `option` tag, but because the `dropdown` module use `button`s to create the dropdown, technically it would be nice to have this possibility (from what I understand, currently html code is stripped when the `button`s are built).

Thanks

**Comment by benplum** [comment]
The option tag doesn't allow for any markup as part of it's content, so it's technically not valid html. I've received this question a few times and unsure of the best way to handle it. As a quick solution, you could try a :before pseudo element on an over-qualified selector, like this:

```
.fs-dropdown-item[data-value="hand"] {
    ...
}
```

But I'm not sure if that's going to work with your icon classing.

**Comment by pensiero** [comment]
Thanks, it could be a solution but not really perfect for my icon classing. However, just an idea: you could use a `data-html` attr specified for each option to display a different html instead of the html content of the option

**Comment by benplum** [comment]
So the data-html would contain the entire `<span class="icon icon-hand"></span> Hello` string? I like this idea and will look into adding to soon.

**Comment by pensiero** [comment]
Exactly! Great :+1:

**Comment by pensiero** [comment]
Works perfectly :+1: thanks a lot
