### ISSUE TITLE
Drag Drop but not click browse supports multiple file selection.

### ISSUE THREAD

**Issue by Valamas** [Formstone/Formstone#50]
UPLOAD CONTROL

The control supports multiple file upload using the drag and drop feature. The click/browse is only a single selection. The generated [input type=file] needs the multiple attribute added.

currently i am doing this in document ready as
$('.fs-upload-input').attr("multiple", '');

where "upload" is the class name via call
$(".upload").upload();

I did not see an option to enable multiple in the docs even though the drag drop uploads multiple files.

**Comment by benplum** [comment]
This is a great point and will hopefully make it to an update soon.

**Comment by benplum** [comment]
I'll have a new version bump up soon.
