### ISSUE TITLE
New Events for File Upload

### ISSUE THREAD

**Issue by ghost** [Formstone/Formstone#51]
First of all I want to thank you for making such an amazing set of components that works beautifully.

I think one of the functionality that would be helpful is to have an event such as onFileAdded. The purpose of this event is to add a certain file to the queue only if user defined validations are passed. Such as you might want to limit file based on it's mime type or any other user defined validation. Alternately you could even use it show activity in any kind of UI as well.

**Comment by benplum** [comment]
This is a great addition. Hopefully it'll make it to an update soon.

**Comment by benplum** [comment]
Added ability to filter uploads in 0.8.21. The `beforeSend` callback now passes 2 parameters, `formData` and `file`. You can cancel an upload based on file attributes by returning `false` instead of the modified `formData` object.
