### ISSUE TITLE
Select component is not compatible with AngularJS's ng-model

### ISSUE THREAD

**Issue by papaiatis** [Formstone/Formstone#52]
The <select> component is not compatible with AngularJs. When I tried to add `ng-model="sortMethod"` the model did not updated when I chose an option element. 
Please add support for AngularJs.

```
<select class="selectpicker" data-style="btn-select" data-width="auto" data-ng-model="sortMethod">

<option value="-createdAt" selected="selected">Last changed</option>

<option value="-price">Price desc</option>

<option value="price">Price asc</option>

</select>
```

**Comment by benplum** [comment]
I don't work with angular and have only cursory knowledge of it's internals. I would love to hear more about how we can add Angular support, but have no immediate plans for implementing anything.

**Comment by cbier** [comment]
@papaiatis have you solved this issue? I am thinking you can hook into the change event that dropdown provides and update your model that way.

```
$("select").on("change", function() {
   $scope.sortMethod = $(this).val();
});
```

**Comment by cbier** [comment]
I stumbled upon this issue because I am trying to use `ng-option` on a `select` element and then initialize the formstone dropdown but dropdown isn't recognizing the values even if I trigger the update method. Still looking into this.

**Comment by benplum** [comment]
Please share anything you find. It would be great to have Angluar support, but it's not something that we're actively investigating.
