### ISSUE TITLE
Upload: Highlight drop area when dragging external file over browser

### ISSUE THREAD

**Issue by Valamas** [Formstone/Formstone#58]
I have tried with my own mouse events without success. I would like it if the drop are highlighted when dragging a file over the browser.

To either highlight as the file is being dragged over the browser or as the file enters the drop down area. Or, a combination of the two. Lighter highlight to indicate a drop area, heavier highlight to show you are in the drop area.

**Comment by benplum** [comment]
You can style the `.fs-upload-dropping` class. This gets added to the `fs-upload` element when you are dragging over the drop zone. 

I'll have a new version bump up soon.

**Comment by Valamas** [comment]
I added the class and bgColor gets added as a style which is not overridden, however, the background is still white when the class is applied. I can't see for the life of me why the box is not turning yellow.
    .fs-upload-dropping
    {
        background-color: #FFFF99 !important;
    }

**Comment by Valamas** [comment]
working well. thank you for the fix.
