### ISSUE TITLE
Light box:How to have  image and video in same gallery?

### ISSUE THREAD

**Issue by AnandAyan** [Formstone/Formstone#59]
Hello this my structure  for my light box ,

 " a href = "resources/images/3.jpg" data-lightbox-gallery="photo_gallery">
                                 img src="resources/images/3.jpg" />
                            </a>
  a href="resources/images/video.mp4" class="test-popup-link"  data-lightbox-gallery="photo_gallery">
                                img src="resources/images/img_ad.jpg.jpg " />
                            </a 
"</code>
its working fine when clicked on individual elements ,but when on gallery mode on click next from image to a video i get "Error Loading Resource" ?

**Comment by benplum** [comment]
You can't load a local video into the lightbox like that - it's not set up to as a video player, but it will load in YouTube or Vimeo embed URLs.
