### ISSUE TITLE
Update a checkbox

### ISSUE THREAD

**Issue by pensiero** [Formstone/Formstone#6]
Before all, congratulations for your great job with the upgrade of all the modules of Formstone!

I'm using React and I change the checkbox "checked" attribute with a state. However, Formstone's checkbox doesn't read the change, but I do not request so much, I just need a function that "update" the checkbox.

Before (with the picker) I used the method "update"

```
$(".target").picker("update");
```

and everything works fine, but now that method does not exist.

How can I solve the problem?

Thanks

**Comment by benplum** [comment]
I see. So React doesn't trigger a change event on the input when it modifies the state?

**Comment by pensiero** [comment]
Yes, I don't know how it works in detail, but it seems that the event
triggered is different than the original, it could be a copy or maybe it
bypass it.

If you need more details, I can search. React is a great language, but I
don't want that you spend time to make your module compatible... An update
method will be fine :)

Oscar
Il 16/apr/2015 08:31 PM, "Ben Plum" notifications@github.com ha scritto:

**Comment by benplum** [comment]
Sure, it's just one of the reason it was removed is that it is redundant (the browser already provides the 'update' functionality with native events). Can you try triggering a change event on update, rather then using the update method?

```
$(".target").trigger("change");
```

**Comment by pensiero** [comment]
In that case the methods go in loop.. the change trigger the state's update, and the state's update trigger the change.

**Comment by pensiero** [comment]
Any news about this? Thanks a lot

**Comment by pensiero** [comment]
Hi @benplum, can you suggest possible workarounds for me? Thanks a lot :)

**Comment by pensiero** [comment]
:+1:  thanks!
