### ISSUE TITLE
Checkbox is not working in Firefox 41

### ISSUE THREAD

**Issue by smartcorestudio** [Formstone/Formstone#62]
It renders but doesn't function. 
Tested both on your demo https://formstone.it/components/checkbox/ and my working environment. Desktop without touchscreen, Windows 10, Firefox 41.
It works OK in Chrome.

**Comment by smartcorestudio** [comment]
This can be fixed by deleting lines 25-27 in "touch.js":

```
if (Formstone.support.touch) {
this.on( [Events.touchStart, Events.pointerDown].join(" "), data, onPointerStart);
} else 
```

**Comment by benplum** [comment]
Are you seeing the no-touch class on the body in the demos? I'm thinking this is related to Windows incorrectly reporting a touch device. I'll look into another method for determining touch.

**Comment by smartcorestudio** [comment]
It works now after you've switched off touch support checking. I've created a new bug in Bugzilla for this https://bugzilla.mozilla.org/show_bug.cgi?id=1197708
