### ISSUE TITLE
Not able to send Radio button value with Upload

### ISSUE THREAD

**Issue by ghost** [Formstone/Formstone#63]
I have a radio button in the same page as upload component.

Whenever somebody clicks on radio button it calls a jquery change function and updates the value of a hidden input variable.

When I upload the file using upload component I see that it is still sending old value of the hidden field. Here is how my code for upload looks like:

```
$('#someCB').change(function() {
    if($(this).is(":checked")) {
          $('#someHiddenVar').val("on");
          }
});

```

Upload component:

```
var cmpDzOptions = {action: uploadUrl, label: cmpLabel, maxQueue: maxQueue, maxSize: maxSize, postData: {batchId: $('#batchId').val(), someHiddenVar:$('#someHiddenVar').val()}};

$("#dropBox").upload(cmpDzOptions)
                    .on("start.upload", cmpOnStart)
                    .on("filecomplete.upload", cmpOnFileComplete)
                    .on("complete.upload", cmpOnComplete);

```

Is there a way I can trigger upload component to update the postData upon change in form values?

**Comment by benplum** [comment]
No, but this would be a good enhancement.

**Comment by benplum** [comment]
There's a new callback for modifying for data on upload where you have access to a standard [Form Data object](https://developer.mozilla.org/en-US/docs/Web/API/FormData):

```
$(".target").upload({
    ...
    beforeSend: modifyData
});

function modifyData(formdata) {
    formdata.append("fieldName", "fieldValue");

    return formdata;
}
```
