### ISSUE TITLE
Can't scroll to bottom position

### ISSUE THREAD

**Issue by Freakmeister** [Formstone/Formstone#66]
Hey, I attached your scrollbar to a chat box, I want it to jump to bottom position after scrollbar was loaded. How can I do this? I tried it like this but it didn't worked:
`$(".chat-wrap").scrollbar('scroll', 'bottom', 0);`
Scrollbar doesn't load this way at all. I even tried to load it first:
`$(".chat-wrap").scrollbar();`
And then do this for a test - no effect:
`$(document).on('click', 'body', function() {`
`$(".chat-wrap").scrollbar('scroll', 'bottom', 0);`
`});`

**Comment by benplum** [comment]
'bottom' isn't a valid keyword, but would make a nice enhancement. For now you could try scrolling to an absurdly large number: `$(".chat-wrap").scrollbar('scroll', 100000000, 0);`

**Comment by benplum** [comment]
The `top` and `bottom` keywords now scrolls content to either the top or bottom.
