### ISSUE TITLE
Dropdown doesn't recognize window limit after latest update

### ISSUE THREAD

**Issue by pensiero** [Formstone/Formstone#68]
After updating Formstone from 0.6.\* to 0.7.\* the dropdown doesn't recognize the upper and lower limits of the container in which is enclosed, if the container has something like `overflow-y: scroll`.

This happen for example in Safari for Mac, and in Chrome for Windows.

I attach a screenshot:
<img width="566" alt="screen shot 2015-08-28 at 11 41 29" src="https://cloud.githubusercontent.com/assets/2010696/9543542/e33d2fb6-4d79-11e5-916f-3b0c14079f33.png">

**Comment by benplum** [comment]
It's always detected based on the edge of the body element. A way to detect from the edge of a parent would be interesting.

**Comment by pensiero** [comment]
Absolutely :+1:

**Comment by benplum** [comment]
Resolved in 1.1.0.
