### ISSUE TITLE
Navigation: Cannot read property 'removeClass' of null

### ISSUE THREAD

**Issue by knation** [Formstone/Formstone#7]
Having trouble initializing as such:

``` html
<h4 id="handle">Navigation</h4>
<nav data-navigation-handle="#handle">
    <a href="#">Home</a>
    <a href="#">About</a>
    <a href="#">Contact</a>
</nav>
```

``` javascript
$(document).ready( function () { 
  $('nav').navigation({
    type: 'overlay',
    maxWidth: '10000px',
    gravity: 'left'
  });
});
```

Receiving an `Uncaught TypeError: Cannot read property 'removeClass' of null - navigation.js:213` error. jQuery v2.1.3

Seems to fail on this line: `$Locks.removeClass(RawClasses.lock);` in `onClose` function.

**Comment by knation** [comment]
Experienced this also with jQuery v1.11.2 and with the minified version of navigation.js.

**Comment by benplum** [comment]
I can't replicate this: http://jsbin.com/buqaroqase/5/edit?html,js,output 
Any more details?

**Comment by knation** [comment]
I'm an idiot and had a dependency issue. SO sorry for wasting your time!

**Comment by benplum** [comment]
No worries, glad you figured it out!
