### ISSUE TITLE
ASAP- opacity: 0

### ISSUE THREAD

**Issue by mkbctrl** [Formstone/Formstone#71]
Hello, 

I think I found an issue in your asap module. It occurs on your page too: https://formstone.it/site/extra/asap/

when you switch from Home to Contact or About the opacity of <div id="content"> remains 0.

**Comment by mkbctrl** [comment]
I think, here's someting what's missing (found in your extra/asap folder):

$content.animate({ opacity: 0 }, 1000, function() {

**Comment by mkbctrl** [comment]
I have added this line: $content.animate({ opacity: 1 }, 1000);

here

function pageLoaded(e) {
    // unbind old events and remove plugins
    console.log("Destroy old page");
    $content.animate({ opacity: 1 }, 1000);
}

and everything works just fine. Is it good solution?

**Comment by benplum** [comment]
This had to do with the event changes in 0.8.1. The demo is now working.
