### ISSUE TITLE
$.asap: $.analytics is not a function

### ISSUE THREAD

**Issue by pyronaur** [Formstone/Formstone#72]
When I navigate the site ( click a link and call asap load ) I get this error
Happening since this recent update:
https://github.com/Formstone/Formstone/commit/5fd5022e481036672a6edb29dddbc499cd1bea51

```
Uncaught TypeError: $.analytics is not a function
```

I think this should be fixed asap ( _ba dum tsss_ :sweat_smile: )

**Comment by benplum** [comment]
Analytics was added as a dependency for ASAP to reduce redundant analytics tracking code. 0.8.4 adds a check for Analytics to avoid breaking, but you should include Analytics to make sure pageviews are still being pushed to GA.

**Comment by pyronaur** [comment]
It still breaks, now with: 
`Uncaught TypeError: $.fsAnalytics is not a function` @ https://github.com/Formstone/Formstone/blob/master/src/js/asap.js#L291

What's up ?

**Comment by benplum** [comment]
Resolved in 0.8.16 - sorry for the confusion on this.
