### ISSUE TITLE
ASAP: Demo Not Working

### ISSUE THREAD

**Issue by pyronaur** [Formstone/Formstone#73]
Demo doesn't show pages when they're loaded since the recent update in ASAP:
https://formstone.it/site/extra/asap/about.php

<img width="1440" alt="screen shot 2015-09-07 at 08 40 47" src="https://cloud.githubusercontent.com/assets/988095/9709889/2a2871d2-553c-11e5-99d0-1a0f3113c0f7.png">

Browser: Chrome 45

**Comment by benplum** [comment]
This had to do with the event changes in 0.8.1. The demo is now working.
