### ISSUE TITLE
dropdown and checker nor working on ie 10 +

### ISSUE THREAD

**Issue by synsuman** [Formstone/Formstone#78]
Hi , the new version of formstone v0.8.10 is not working on IE10+, IE Edge

The dropdown wont open on clicked and fs-dropdown-open class also doesn't show on ie.

How ever this works on ie 9.

simlarly checkbox checker is not working on checkbox but working for radio input.

Can you please suggest what to do here.

Thanks in advance

**Comment by benplum** [comment]
Fixed in 0.8.11.
