### ISSUE TITLE
upload: disable not working

### ISSUE THREAD

**Issue by tomzooi** [Formstone/Formstone#79]
I want to do this in my code:
on("filestart", function(event,file) {
                  console.log("upload started");
                  $("#upload_target").upload("disable"); //disbable temporarily

it does not work however, I can still drag in files. I can only make it sort of work using:
on("filestart", function(event,file) {
                  console.log("upload started");
                  $("#upload_target").hide(); //disbable temporarily

**Comment by benplum** [comment]
I can't replicate this. Can you provide an example (jsbin or codepen)?
