### ISSUE TITLE
Upload component is not working in Snow leopard (iOS 10) + Safari 

### ISSUE THREAD

**Issue by kuldip-plenar** [Formstone/Formstone#80]
Upload component is not working in Snow leopard (iOS 10.X) + Safari.

**Comment by benplum** [comment]
I can't replicate this, can you provide an example (jsbin or codepen)?

**Comment by kuldip-plenar** [comment]
Just visit your upload demo in Snow leopard (iOS 10.X) + Safari.
https://formstone.it/components/upload/

**Comment by benplum** [comment]
Do you mean OSX 10.x? Snow leopard is quite old and that version of Safari does not support the file API (http://caniuse.com/#feat=fileapi). You will need to provide a fallback for these users. You can test for support with `Formstone.support.file`.
