### ISSUE TITLE
YouTube Video not allow fullScreen

### ISSUE THREAD

**Issue by berj** [Formstone/Formstone#81]
I tried the Lightbox demo on this page (https://formstone.it/components/lightbox/).

For Youtube Video when I click on the fullScreen button, it said « FullScreen is not available ». For Vimeo it is OK I can access to fullScreen.

When I will use LightBox, do I will have option to activate the fullScreen for Youtube video?

OS X 10.10.4
Safari 8.0.7
Chrome 45.0.2454.93
Firefox 40.0.3
Opera 32.0.1948.25

Thank you

**Comment by benplum** [comment]
Resolved in 0.8.16
