### ISSUE TITLE
core:use webpack error

### ISSUE THREAD

**Issue by minuux** [Formstone/Formstone#84]
Hi

I use webpack pack my code,but chrome say 

```
 Cannot read property 'navigator' of undefined
```

my code:

```
var $ = require('jquery');
require('formstone/src/js/core.js');
require('formstone/src/js/tooltip.js');
require('formstone/src/less/tooltip.less');
```

I check core.js,find the **this** is undefined

```
var Formstone = this.Formstone = (function ($, window, document, undefined) {

})(jQuery, this, document);
```

so I changed above the code as below,then it work

```
var Formstone =window.Formstone = (function ($, window, document, undefined) {

})(jQuery, window, document);
```

Do you have a better way？

**Comment by benplum** [comment]
Formstone isn't built with AMD loading in mind and always assumes this refers to the window object. We can look into changing this in a future release.

**Comment by benplum** [comment]
Resolved in 0.8.18.

**Comment by ajbeach2** [comment]
this is still broken in the npm version 0.5.1

**Comment by benplum** [comment]
Any details on the error you're experiencing?

**Comment by minuux** [comment]
try https://github.com/webpack/imports-loader

replace **this**

**Comment by benplum** [comment]
AMD module support added: https://github.com/Formstone/Formstone/commit/c2a04e3d53085c7d86b5685f01100de3e51f6dcd
