### ISSUE TITLE
Lightbox - Cannot set minWidth & minHeight

### ISSUE THREAD

**Issue by raducretu** [Formstone/Formstone#85]
Hi there,

It seems I cannot set the minWidth & minHeight. It remains on 200px wide and going as needed on vertical. The code I use is:

```
    $(function() {
        $("a.lightbox").lightbox();
    });
```

I can set correctly any other default, by any method, either data- either from JS, and they work.

Thank you

**Comment by raducretu** [comment]
Also, I forgot to add, that if I resize the window to smaller, it works fine ...

**Comment by benplum** [comment]
I'm not sure what the issue is. Can you provide and example (jsbin or codepen)?
