### ISSUE TITLE
Theme support

### ISSUE THREAD

**Issue by benplum** [Formstone/Formstone#87]
Move all style specific CSS to theme files. Keep any positioning CSS necessary for component to function and/or render. 2 themes to start (light and dark).

**Comment by trinzia** [comment]
Can be accomplished purely via css, so no need for more than two (if that).

**Comment by benplum** [comment]
Yup, the idea is that anything not related to basic structure will be moved out to a theme file. Developers could then create their own themes for use in projects. The library would contain 2 options as examples.

**Comment by benplum** [comment]
Theme support is planned for the 0.9.0 release. The goal is to further separate the structure and functionality of a component from the visual styles, allowing developers to more easily customize an individual component without needing to override and repeat as many styles. Themes are essentially CSS classes added to the component, similar to the `customClass` option found in many plugins. All styles not integral to the function of the component will be moved to separate files containing scoped, theme-specific selectors. The default theme will be named 'Light' (`fs-light`) and match the current component designs, as well as introduce new styles for previously un-styled components, like Pagination. Full theme files can be included, or individual component-specific theme files can be compiled from `src`. 

Note: This will not be a drop in upgrade because of the CSS selector specificity changes required. Code updates should be minor (if including the 'Light' theme), and will usually involve simply modifying custom selectors to match the new specificity. 

A 0.8.x branch will continue to be supported into 2016, however developers are encouraged to upgrade to take advantage of the lighter, less restrictive code base, especially on heavily customize interfaces.

**Comment by benplum** [comment]
Test drive themes here: [beta.formstone.it/themes](http://beta.formstone.it/themes)

**Comment by trinzia** [comment]
Specificity of selectors is always appreciated!  I enjoy your work, very thoughtful.

I have an idea that you could allow calling themes like this: `data-theme="neon"`.  Then the widget would have the prefix 'neon' on all appropriate styles.  The defaults could be simple light and dark, but allowing other names would allow authors to create their own, as well.  

Use case: I have scrollbars placed in 3 different colored boxes, and would like to make different coloring for each.

Just a thought, maybe it's useful, maybe not. :)

**Comment by benplum** [comment]
You are already able to define options for any 'widget' plugin by setting a namespaced 'options' attribute, this would just be a key off of that same JSON attribute:

```
<div class="js-carousel" data-carousel-options='{"theme":"custom_theme"}'/>
    ...
</div>
```

This will allow you to theme like so:

```
.fs-carousel.custom_theme {
    ...
}

.fs-carousel.custom_theme .fs-carousel-control {
    ...
}

...
```

**Comment by benplum** [comment]
Theme support landing on March 21, 2016.
