### ISSUE TITLE
Resizing dropdown scrollbar

### ISSUE THREAD

**Issue by cbier** [Formstone/Formstone#88]
I am trying to resize the width of the scrollbar in the dropdown options to 11px instead of 16px. The buttons do not fill in the newly available space for some reason even though their width is 100%.

![image](https://cloud.githubusercontent.com/assets/2236701/10198398/d18a2f58-6769-11e5-88a1-6d3e19dbbd88.png)

**Comment by cbier** [comment]
I have been trying to figure this out for a couple hours and even tried sandboxing it on codepen but I'm unable to reproduce the issue.

If I remove `max-height` from `.fs-scrollbar-content` the buttons will fill the entire width of `.fs-scrollbar-content`
Also, if I remove `line-height` and `height` from the buttons, the buttons will fill the entire width of `.fs-scrollbar-content`

Unfortunately both of those changes break the scrolling. I also don't know why removing those properties "fixes" the issue

Any ideas? Thanks!!!!

**Comment by benplum** [comment]
Can you provide an example? (Codepen or jsbin)
