### ISSUE TITLE
Possibility to set the Xhr dataType

### ISSUE THREAD

**Issue by boussou** [Formstone/Formstone#89]
I need it to for a generic UT check.  I need the datatype to be always set on XHR callback, and I need to set a Json answer type.

So I would propose a change like following:
1/
add dataType to options
    var options = {
         ...
          dataType: 'html'  //dataType (default: Intelligent Guess (xml, json, script, or html))
    };
2/
use it in the ajax call

```
file.transfer = $.ajax({
            ...
            dataType: options.dataType,
```

**Comment by benplum** [comment]
Added `dataType` option in 0.8.21.
