### ISSUE TITLE
Scrollbar update?

### ISSUE THREAD

**Issue by trinzia** [Formstone/Formstone#92]
Hi,
My scrollbar isn't loading until I resize browser.  It's placed in a complex layout, but basically a modal, with content show() after my modal animates.  Scrollbar only loads when I resize browser window.

Is there a way to force load, like .scrolllbar('update') ?

PS - Using version downloaded today.
Thanks.

**Comment by benplum** [comment]
You should be able to trigger a resize event when the modal opens to force the scrollbar to update. If the content is hidden at initialization the scrollbar won't be able to calculate a layout.

**Comment by trinzia** [comment]
I tried using resize, but it didn't force the scrollbars to show.

**Comment by benplum** [comment]
Do you have an example? (Codepen or jsbin)

**Comment by trinzia** [comment]
JSFiddle seems ok, can delete issue.  
https://jsfiddle.net/1k5L6hno/4/

I have something funny going on with CSS, probably.  Will try removing some floats, etc.
