### ISSUE TITLE
Suggestion: Range: Fill volume 

### ISSUE THREAD

**Issue by trinzia** [Formstone/Formstone#93]
Suggestion for range slider:

I would like an option for a 'volume' bar, which basically fills up the range from left, with some bright color.

Also, can you make the click area larger for grabbing the handle?  I tried some things but IE failed with background-clip combined with border-radius.  I'd like it to appear the same size, but have a larger click/drag spot.  For big thumbs etc.

Also not working in ie8/9.  I'm not allowed to drop those yet. 

Thanks.

**Comment by benplum** [comment]
The bar does not currently have a "fill", but this would be a nice enhancement. 

I'll check on the ie8/9 issues.

**Comment by benplum** [comment]
Added `fill` option in 0.8.21.

**Comment by trinzia** [comment]
I figured out how to make the click area bigger, by using :before and :after to create the visible graphic while the parent divs are larger than is seen.  Seems to work fine.  Posting for Googlers:

```
   .fs-scrollbar-track {
    width: 20px;
    height: 100%;
    position: absolute; right:0;
    overflow: hidden; }

  .fs-scrollbar-track:after {
    content:"";
    display:block; width:6px; height:100%; 
    position:absolute; top:0; right:4px; 
    background: #e5e5e5;
    border-radius:3px;
  }  

  .fs-scrollbar-handle {
    width: 20px;
    height: 20px;
    position: absolute;
    top: 0;
    right: 0px;
    z-index: 2;
    cursor: pointer; }

  .fs-scrollbar-handle:after { 
    content:"";
    display:block; width:6px; height:100%; 
    position:absolute; top:0; right:4px; 
    background: #555;
    border-radius: 3px;
  }
```
