### ISSUE TITLE
XSS issue

### ISSUE THREAD

**Issue by etdsoft** [Formstone/Formstone#95]
Hi @benplum, thanks for your work on this library.

We've found an XSS issue, how do you prefer to discuss it?

**Comment by benplum** [comment]
Feel free to email me: mr@benplum.com

**Comment by benplum** [comment]
Any update on this?

**Comment by etdsoft** [comment]
Sorry, sent.

**Comment by benplum** [comment]
Fixed in [ef73635](https://github.com/Formstone/Formstone/commit/ef7363527e3edde94af0b2b9a66923fa63aa16c3), will make it in the next bug fix release.
