### ISSUE TITLE
iOS9 Safari bug

### ISSUE THREAD

**Issue by pyronaur** [Formstone/Formstone#96]
Safari, iOS9

```
TypeError: null is not an object (evaluating 'state.id')
onPoplibs.js:5289
dispatchjquery.js:1427:244
handlejquery.js:1366:112
```

Screenshot:
<img width="1304" alt="screen shot 2015-10-13 at 20 08 31" src="https://cloud.githubusercontent.com/assets/988095/10462245/5619f718-71e6-11e5-8918-b57354dfba5a.png">

**Comment by benplum** [comment]
Any details here? Was this on load? When navigating back or forward? Was this the demo site or an example you can share?

**Comment by pyronaur** [comment]
Hi Ben,
Sorry for the delay, been extremely busy.
Yes, this happens on page load and on your demo site: https://formstone.it/site/extra/asap/

**Comment by benplum** [comment]
I can't replicate this in the simulator with iOS 9.0 or 9.1.

**Comment by pyronaur** [comment]
Try the desktop version of safari.

On Tue, Nov 17, 2015 at 3:50 PM -0800, "Ben Plum" notifications@github.com wrote:

I can't replicate this in the simulator with iOS 9.0 or 9.1.

**Comment by benplum** [comment]
Finally tracked this down, I'lll tag a new release soon.
